### ISSUE TITLE
Can't figure how to add babel plugin

### ISSUE THREAD

**Issue by neovea** [symfony/webpack-encore#100]
Hi, is webpack encore designed to permit adding babel plugins ?
I'm willing to use configureBabel to add support of style-jsx (from here : https://github.com/zeit/styled-jsx) but can't find the syntax to use for that.
Thanks for helping out :)

**Comment by grimpows** [comment]
same for me, doc show only how to add preset and not plugins, i tryed replace .preset by .plugin dut dont work, may its not implementend or not in doc yet ^^, atm i use a babelrc with 


{
  "presets": ["es2015", "react"],
  "plugins": ["transform-object-rest-spread"]
}

**Comment by weaverryan** [comment]
Hey guys!

You should indeed be able to replace `.preset` with `.plugin` from this page... with one small difference: http://symfony.com/doc/current/frontend/encore/babel.html. So:

```js
Encore
    // ...

    // first, install any presets you want to use (e.g. yarn add babel-preset-es2017)
    // then, modify the default Babel configuration
    .configureBabel(function(babelConfig) {
        babelConfig.plugins = ['styled-jsx/babel']
    })
;
```

The small difference being to assign the entire array, instead of just `.push`. That `babelConfig` variable already has a `presets` key, but it does not have a `plugins` key (so you can't use push).

But also, a better way is to create a `.babelrc` file - that's the best-practice for configuring babel (we just try to give you some nice default config that works for 95% of people). Here is the default config we use, in case you want to start your `.babelrc` file with that: https://github.com/symfony/webpack-encore/blob/4ad8d880c2ea62cf2bb3d7404db6e3a375cbc17d/lib/loaders/babel.js#L30-L44

I'm going to tweak the docs a little bit about this topic.

Cheers!

**Comment by grimpows** [comment]
thanks for this great answers, but adding a empty plugins array would be better to fit with how presets are handled with encore no ?

**Comment by weaverryan** [comment]
Yea... and I suppose it would be safer (you could .push or override it entirely) - I'll make that change - see #107

**Comment by neovea** [comment]
Thanks, this works. I tried to follow the same pattern as presets and pushing, wasn't working.
I agree with @grimpows about `babelConfig.plugins.push`, it will be less confusing.

**Comment by weaverryan** [comment]
@neovea the docs are already updated with an example on how to add a Babel plugin :). Though, we'll simplify that example a bit further after the PR is merged to allow `babelConfig.plugins.push`.

Cheers!
