### ISSUE TITLE
[Feature] Stylelint Plugin functionality

### ISSUE THREAD

**Issue by tropicalraisel** [symfony/webpack-encore#1022]
Similar to ESLint, but for CSS and SASS: https://www.npmjs.com/package/stylelint

**Comment by versedi** [comment]
Already achievable via: https://webpack.js.org/plugins/stylelint-webpack-plugin/

```
const StylelintPlugin = require('stylelint-webpack-plugin');

Encore.addPlugin(new StyleLintPlugin());

```

written from hand.

I advise to not use it, IMHO eslint is the thing to use and also works with webpack.

**Comment by TropicalRaisel** [comment]
I'm aware; this project is just based around providing features through small statements. I figured Stylelint would be a good addition since ESLint doesn't handle styles. Since it's a plugin maybe it should be used as a loader, but I've seen other issues and PRs about updating the `enableEslintLoader()` to `enableEslintPlugin()`. Therefore, if that's acceptable adding Stylelint support should be ok.

**Comment by TropicalRaisel** [comment]
Hold off on this until Stylelint [supports PostCSS 8](https://github.com/stylelint/stylelint/issues/5506).

**Comment by Kocal** [comment]
Closing for the same exact reasons from https://github.com/symfony/webpack-encore/issues/1267#issuecomment-2302708857
