### ISSUE TITLE
Alpinejs async method results in Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by galaczi** [symfony/webpack-encore#1114]
I am trying to bundle some files that use Alpinejs. I need an async method that uses fetch and I am getting ``Uncaught ReferenceError: regeneratorRuntime is not defined``. I found a couple references to the issue pointing to https://babeljs.io/docs/en/babel-plugin-transform-runtime. I have installed them and tried to configure it as required:

```
Encore.configureBabel((config) => {
  config.plugins.push('@babel/plugin-transform-runtime', {regenerator: true});
})
```

Example Alpine code:

```
import Alpine from 'alpinejs'

Alpine.data('fetchTest', () => ({
  async init() {
    return 'hi'
  }
}))

Alpine.start()
```
But the error never goes away. Any ideas?

**Comment by stof** [comment]
Well, if `alpinejs` is shared on npm without using `babel-plugin-transform-runtime`, then you need to expose `regenerator-runtime` as the `regeneratorRuntime` global variable (you might use `Encore.provideVariables` to emulate that).

Solving the issue by using `babel-plugin-transform-runtime` is the fix that can be applied by the alpinejs package, not by consumers of the package.

**Comment by galaczi** [comment]
Thanks for the answer! Alpine is not coupled with any bundler so no, it doesn't come with any babel plugins.

If I may inquire further, I don't understand why I would even need the ``regenerator-runtime`` for async functions? Alpine doesn't have it as a dependency.

**Comment by stof** [comment]
`babel-plugin-transform-runtime` is not coupled to any bundler either. It will only generate a `require('regenerator-runtime')` (or `import 'regenerator-runtime'` if you configure it to generate ES imports) instead of relying on accessing a global `regeneratorRuntime` variable.

And if alpinejs transpiles its code with babel to turn async functions into normal functions, it *must* depend on `regenerator-runtime` as it will indeed depend on them.

**Comment by galaczi** [comment]
I solved it with:

```
Encore.configureBabel(function(babelConfig) {
  babelConfig.presets = ['es2015','stage-2']
  babelConfig.plugins = ['transform-runtime']
})
```
