### ISSUE TITLE
Dropped support for Vue2 in 4.0.0 ?

### ISSUE THREAD

**Issue by Pyreweb** [symfony/webpack-encore#1156]
Hi,

I'm still using VueJS 2 and if I upgrade to Encore 4.0.0 I get a dependancy conflict on npm install :

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @qualiteval/incidents@6.4.0
npm ERR! Found: vue@2.7.13
npm ERR! node_modules/vue
npm ERR!   vue@"^2.7.13" from the root project
npm ERR!   peerOptional vue@"*" from @vue/babel-preset-jsx@1.4.0
npm ERR!   node_modules/@vue/babel-preset-jsx
npm ERR!     peerOptional @vue/babel-preset-jsx@"^1.0.0" from @symfony/webpack-encore@4.0.0
npm ERR!     node_modules/@symfony/webpack-encore
npm ERR!       dev @symfony/webpack-encore@"^4.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional vue@"^3.2.14" from @symfony/webpack-encore@4.0.0
npm ERR! node_modules/@symfony/webpack-encore
npm ERR!   dev @symfony/webpack-encore@"^4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

It was not mentionned in the changelog, can you confirm that was intentional ?

**Comment by weaverryan** [comment]
Hi!

Thanks for the report - indeed, that was unintentional. @Kocal I think we accidentally required v3 only of vue as a peer dependency (I think it's because v3 was listed as a `devDependency` before and now - we use a trick in `scripts/force-lowest-dependencies.js` to force Vue down to 2 for the CI).

I think it should be as "simple" as correcting the `peerDependencies` version for Vue? We also need to allow `^15.0.11` or greater for `vue-loader`. So, I think we'll need something like `^15.0.11|^17.0.0` for `vue-loader`, as I believe vue-loader 16 and 17 are Vue 3 only.

**Comment by Kocal** [comment]
Hi, I'm gonna work in it, thanks @weaverryan for the solution :)

**Comment by Pyreweb** [comment]
> So, I think we'll need something like ^15.0.11|^17.0.0 for vue-loader, as I believe vue-loader 16 and 17 are Vue 3 only.
Yes, I think that since v16 it's for Vue3 only. I use "vue-loader": "^15.10.0",

**Comment by stof** [comment]
@Pyreweb opening an issue would be much better than commenting on a closed ticket
