### ISSUE TITLE
Option to order the scripts generation?

### ISSUE THREAD

**Issue by Herod** [symfony/webpack-encore#117]
Is there a way to order how scripts are added to the compiled file? (I noticed that if i export for production it loads the file in the specified order, but for dev not)

for example I have something like:

```javascript
require('./adminScripts');
require('./registrationDocuments');
require('./institutions');
```

But the content of the file is generated in alphabetical order (in dev):
- admin scripts
- institutions
- registration documents

What if i need to load a 3rd party library first?
I know there is the option to add sharedEntry but I cannot make this available for multiple files like admin, users, etc.

And also do we need all those comments in the production generated file?

**Comment by Lyrkan** [comment]
Hi,

The order in which things are in the compiled output file shouldn't matter.

If one or your modules (e.g. `registrationDocuments`) need another module (e.g. `adminScripts`) then you should import that last one into the first one (e.g. `adminScript` into `registrationDocuments`).

Since Webpack creates a graph of all the dependencies it already knows when/where things should be loaded and will generate the output files accordingly.

That works for 3rd party libraries too: if a library can be imported as a module (which is the case for many of them), just import it into the files that'll be using it, Webpack should take care of the rest.

**Comment by weaverryan** [comment]
Exactly as @Lykran said :). That's the power of webpack actually! @Herod are you seeing some sort of error or bad behavior?

About the comments in the final file, if you're running "encore production", there should be no comments. If you're seeing something different, let me know - that would indeed be a bug :)

**Comment by Herod** [comment]
Ok, I got the idea but it seems to be a bit "magic". Anyway, thanks you guys for the help.

**Comment by weaverryan** [comment]
@Herod Haha, indeed. You *really* need to focus on writing your source code correctly - e.g. using `require` to fetch your dependencies. Webpack does quite a bit when you build to make sure it all works.

Btw, instead of:

```js
require('./adminScripts');
require('./registrationDocuments');
require('./institutions');
```

You should start to organize your JS files into smaller files that export values (e.g. functions, objects, whatever). For example:

```js
// adminScripts.js
module.exports = {
    func1() {

    },

   func2() {

    }
}
```

```js
// then use those functions from some other file
var adminFunctions = require('./adminScripts');

adminFunctions.func1();
```

Doing this wasn't possible before the `require` function. If you slowly refactor your code into more re-usable chunks, Webpack will make more and more sense :).

Cheers!
