### ISSUE TITLE
Allow writing configuration instead of code

### ISSUE THREAD

**Issue by Koc** [symfony/webpack-encore#12]
Webpack-encore configuread like many other nodejs build tools - by writing code. But this looks so strange in Symfony's ecosystem. We don't write `$routeCollection->add(new Route('/about'))` usually). We are using configuration by yml/xml.

Why not create semantic configuration like in https://github.com/romanschejbal/gassetic or even just reuse Gassetic? See also https://github.com/romanschejbal/gassetic/issues/62 for alternative integration of Gassetic with Symfony.

**Comment by stof** [comment]
@Koc such semantic config would be very hard to maintain: we would have to update it each time webpack adds a new feature, otherwise the feature will not be available. And it would be quite hard to build a semantic config giving you access to the whole webpack power.

Encore is a builder for the Webpack config object. And a nice thing is that you can still alter the config after Encore generated it in case you have custom needs.
Thus, it would force to tie Encore to Symfony, while it is currently totally independent (the only relation to Symfony in this package are the package name and the maintainers).

Btw, the way GAssetic works is that it generates a file in the Symfony side, which is then used by the node.js side.
Nothing forbids you to create a bundle exposing a semantic config which would be used to generate a webpack.config.js file instead of writing the webpack.config.js yourselves (or, to keep allowing customization, generate a separate file, which can then be required in webpack.config.js)

**Comment by weaverryan** [comment]
I agree with Stof. And I think we should try to minimize the number of abstractions on top of webpack. Right now, if Encore doesn't support something, it's still possible (and simple) to add it to the final, generated configuration (and the webpack documentation applies perfectly).

I'm closing with a 👎 for now

**Comment by stof** [comment]
@weaverryan thus, if someone wants to build a Symfony bundle generating the Encore config based on some semantic config, it would not belong in Encore anyway (and I know I would not use this bundle)
