### ISSUE TITLE
React Ux - enableReactPreset not working

### ISSUE THREAD

**Issue by CesarScur** [symfony/webpack-encore#1215]
Hello friends 👋 
I'm having an interesting problem when following the installation for [react ux](https://symfony.com/bundles/ux-react/current/index.html).

`yarn watch` cries:
```
Syntax Error:
  2 |
  3 | export default function (props) {
> 4 |     return <div>Hello {props.fullName}</div>;
    |            ^
  5 | }

Add @babel/preset-react (https://github.com/babel/babel/tree/main/packages/babel-preset-react) to the 'presets' section of your Babel config to enable transformation.
```
Then changing the config this way fixes it:
```php
    //.enableReactPreset()
    .configureBabel(function(babelConfig) {
        babelConfig.presets.push('@babel/preset-react');
    })
```

-------
There is another error in the documentation but I'm not sure if this is the venue to address it too. In all cases Someone can redirect me.
```js
registerReactControllerComponents(require.context('./react/controllers', true, /\\.(j|t)sx?$/));
// this line appears to have an extra \ right                                   ^ here
```

**Comment by weaverryan** [comment]
Typo in the docs is fixed now - it got that extra \ added with some recent recipe changes.

About your original error, it's odd because the entire point of `enableReactPreset()` is to add `@babel/preset-react` to the react presets - you can see the logic right here - https://github.com/symfony/webpack-encore/blob/4b2511268a1c22a0f4b3fe404028c4cf7f0b3978/lib/loaders/babel.js#L67-L71

I'm going to close this as, likely some weird, local issue. This code hasn't changed in a long time and it's worked for a long time. But if it continues to not work and you can isolate the issue, please reopen!

Cheers!
