### ISSUE TITLE
Support eslint 9

### ISSUE THREAD

**Issue by garak** [symfony/webpack-encore#1267]
Current output:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @symfony/webpack-encore@4.6.1
npm ERR! Found: eslint@9.1.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.1.1" from the root project
npm ERR!   peer eslint@"^6.0.0 || ^7.0.0 || >=8.0.0" from @eslint-community/eslint-utils@4.4.0
npm ERR!   node_modules/@eslint-community/eslint-utils
npm ERR!     @eslint-community/eslint-utils@"^4.2.0" from eslint@9.1.1
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional eslint@"^8.0.0" from @symfony/webpack-encore@4.6.1
npm ERR! node_modules/@symfony/webpack-encore
npm ERR!   dev @symfony/webpack-encore@"^4.6.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint@8.57.0
npm ERR! node_modules/eslint
npm ERR!   peerOptional eslint@"^8.0.0" from @symfony/webpack-encore@4.6.1
npm ERR!   node_modules/@symfony/webpack-encore
npm ERR!     dev @symfony/webpack-encore@"^4.6.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```

**Comment by kumardeepakme** [comment]
Yes, `eslint 9` & `postcss-loader 8`
 
![jMz1eujd20240501104525PMyCJsLh6C](https://github.com/symfony/webpack-encore/assets/36254505/bea5c779-5c0d-4aa0-ae17-fd72b8874998)

**Comment by rugbymauri** [comment]
should be fixed in #1258

**Comment by garak** [comment]
> should be fixed in #1258

But I don't see any change related to eslint there. Indeed, the proposed changes in the PR still use eslint 8.

**Comment by Kocal** [comment]
Hello everyone!

I don't think ESLint 9 will ever be supported. What's more, I'm planning to remove ESLint support from Webpack Encore, and there are several reasons for this:  
1. "Linting while building" was really popular years ago, but things have changed. People now prefer to lint their code as a separate task (in their IDE, in a pre-commit git hook, in a dedicated command, in CI, etc.), and I'm one of them. It slows you, either when you have to lint your code to finally build it, or because the ESLint/ESLint plugin slowness added to the building process.
Also, see https://github.com/vuejs-templates/webpack/issues/73. :) 
2. Supporting ESLint in Webpack Encore has not been without its challenges. It required a lot of work (...) and sometimes involved some hacks to get things working (I really want to remove the "sync-rpc" dependency).  
3. There are far more efficient alternatives, like Biomejs, Oxlint, etc., and I don't want to see support for these in Encore. Code linting should not be related to a **bundling tool**.

I plan to deprecate ESLint support in the next minor version and drop it in the next major version, but I'm open to discussion!

**Comment by stof** [comment]
@Kocal I totally agree with that decision (personally, I never enabled the ESLint integration in Encore, while I'm using ESLint since longer than I'm using Encore)

**Comment by garak** [comment]
@Kocal it's fine for me. My only concern is the error I reported above, if to fix it you have to remove eslint support, go for it.

**Comment by Kocal** [comment]
> My only concern is the error I reported above, if to fix it you have to remove eslint support

Yes, after removing the integration, ESLint dependencies will be your concern!

**Comment by Kocal** [comment]
Closing, as ESLint integration has been removed in #1309 for the next major version of Encore (5).
