### ISSUE TITLE
jQuery slim

### ISSUE THREAD

**Issue by Sozialarchiv** [symfony/webpack-encore#128]
Is there a way to use jquery slim with autoProvidejQuery?

**Comment by Lyrkan** [comment]
Hi @Sozialarchiv,

If the module is called `jquery-slim`, then you can't directly use `autoProvidejQuery` since it'll try to import `jquery`.

However, you can probably achieve what you want by calling [autoProvideVariables](https://github.com/symfony/webpack-encore/blob/master/index.js#L229-L248) instead:

```js
Encore.autoProvideVariables({
    $: 'jquery-lite',
    jQuery: 'jquery-lite',
    'window.jQuery': 'jquery-lite',
});
```

**Comment by weaverryan** [comment]
Perfect explanation! Let us know if you still have any issues :).

**Comment by Sozialarchiv** [comment]
Thank you for this great explenation.
