### ISSUE TITLE
The manifest.json is not created when i enable "webpack-dev-server"

### ISSUE THREAD

**Issue by slince** [symfony/webpack-encore#135]
command:  `encore dev-server --hot`
configuration:
```js
if (!Encore.isProduction()) {
    Encore.enableVersioning(false);
    Encore.setPublicPath('http://127.0.0.1:8080')
        .setManifestKeyPrefix('build/');
}
```

when i visit  "http://127.0.0.1:8000", i got an error:
```
An exception has been thrown during the rendering of a template ("Asset manifest file "C:\www\dish/web/build/manifest.json" does not exist.").
```
If I missed something please tell me, thank you

**Comment by Lyrkan** [comment]
Hi @slince,

That's odd, I did a quick test using the configuration you gave in your post and running `yarn encore dev-server --hot` creates the `manifest.json` file as expected:

![encore-manifest](https://user-images.githubusercontent.com/850046/29017950-665afc48-7b59-11e7-9b20-513f30cc51f4.png)

Does it work fine if you use `dev` instead of `dev-server`?

**Comment by slince** [comment]
@Lyrkan  
Yes, the manifest.json will be created if execute the command 'encore dev'.

**Comment by slince** [comment]
@Lyrkan 
i have removed all files in /node_modules and reinstall theme.  now it works ok.
so strange.
