### ISSUE TITLE
default package.json

### ISSUE THREAD

**Issue by rophini** [symfony/webpack-encore#156]
Hi,

When I install webpack-encore, it comes with a package.json inside. But I already have a package.json file. Is there an option to use my already existing package.json file or do I have to combine them?

**Comment by Lyrkan** [comment]
Hi @rophini,

> it comes with a package.json inside

Are you talking about the `node_modules/@symfony/webpack-encore/package.json` file?

Every `npm`/`yarn` dependency will have a similar file in order to provide metadata about it (name, version, dependencies, scripts, binaries, ...).

Your `package.json` file should only include what **you** are using in your project.

**Comment by rophini** [comment]
Oh, I See, my mistake. I was confused with adding the 'package.json' to git and node_modules to gitignore. I just need to add my package.json to git. thanks for your quick answer!
