### ISSUE TITLE
configureFilenames hash after question mark

### ISSUE THREAD

**Issue by thejahweh** [symfony/webpack-encore#160]
There is a problem when I try to set the chunkhash after the question mark:
```js
.configureFilenames({
    js: '[name].js?[chunkhash:16]'
})
```
Outputs:
```
Error: Problem deleting JS entry for style: 0 files were deleted
at compilation.chunks.forEach 
  (/node_modules/@symfony/webpack-encore/lib/webpack/delete-unused-entries-js-plugin.js:41:27)
```
This works for css, images and fonts, but not for js.

**Comment by Lyrkan** [comment]
Hi @thejahweh,

I guess you are also using `addStyleEntry` ?

The issue is caused by a part that delete "fake" js files created by that method (since adding a CSS file as an entry point is not something native in Webpack), and in this case it gets a bit lost because something like `style.js?c84caea6dd12bba7` doesn't end in `.js`.
