### ISSUE TITLE
Question: How to clean output folder (using "cleanupOutputBeforeBuild") in --watch mode?

### ISSUE THREAD

**Issue by aleixfabra** [symfony/webpack-encore#162]
Now, if it is executed, **it does not clean the output folder when files change**:
```
# recompile assets automatically when files change
$ ./node_modules/.bin/encore dev --watch
```

Instead, it does: 
```
# compile assets once
$ ./node_modules/.bin/encore dev
```

**Comment by Lyrkan** [comment]
Hi @aleixfabra,

This issue was already discussed in #158.

To sum it up: we can't really do anything right now. The [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin) (enabled when you call `cleanupOutputBeforeBuild`) only provides a `watch` option that would delete **everything** and not only invalidated files.

**Comment by aleixfabra** [comment]
Thanks @Lyrkan!
