### ISSUE TITLE
Control over plugin order

### ISSUE THREAD

**Issue by stof** [symfony/webpack-encore#163]
Currently, custom plugins are registered last. but this can cause issues:

- when using the copy-webpack-plugin (assuming plugins are releasing versions containing the support for manifest and copy together), you need to register it before the manifest plugin AFAIK (otherwise the manifest won't see the new entries)
- when using some plugins altering the JS code, you are likely to want them registered before the UglifyJS plugin, so that the final file is minified.

Other examples may come.

I don't know whether we should build a way to control the order precisely, or whether we should just change the position of custom plugins.

**Comment by Lyrkan** [comment]
Hey @stof,

What do you think about something like this?

```js
const webpack = require('webpack');
const ManifestPlugin = require('webpack-manifest-plugin'); // Not the one currently used
const Plugin1 = require('plugin1');
const Plugin2 = require('plugin2');
const Plugin3 = require('plugin3');

Encore
  .addPlugin(new Plugin1())
  .addPlugin(new Plugin2())
  .addPlugin(new Plugin3())
  .sortPlugins([
    Plugin1,
    webpack.optimize.UglifyJsPlugin,
    Plugin2,
    Plugin3,
    ManifestPlugin
  ]);
```

Then just before [this return](https://github.com/symfony/webpack-encore/blob/master/lib/config-generator.js#L243) we would reorder `webpackConfig.plugins` so:

* all instances of Plugin1 are added before instances of UglifyJsPlugin
* all instances of UglifyJsPlugin are added before instances of Plugin2
* all instances of Plugin2 are added before instances of Plugin3
* etc.

This should work if we don't have multiple instances of the same plugin that need to be sorted relatively to each other (which can already be done for custom plugins by calling `addPlugin` in the right order).

I would also move the manifest-plugin after the custom plugins by default in order to avoid the issue with the copy-webpack-plugin.
