### ISSUE TITLE
How to find all js in Sf project?

### ISSUE THREAD

**Issue by xorgxx** [symfony/webpack-encore#169]
How i can do something like this
```// Javascript
gulp.task('App-js', function() {
    return gulp.src([
        '!**/js/**/no/*.js',
        // '!**/js/**/no/*.js',
        '!**/ConstructorBundle/**/js/**/*.js',
        '!**/js/**/datepiker/**/*.js',
        '!**/js/**/Backend/**/*.js',
        '!**/important/*.js',

        'dev-info/Goodis/M.A.J//HTML/js/plugins-1.js',

        // COMPONENTS ===============================
        'dev-info/Goodis/M.A.J//HTML/js/components/bs-datatable.js',
        'dev-info/Goodis/M.A.J//HTML/js/components/bs-filestyle.js',
        'dev-info/Goodis/M.A.J//HTML/js/components/bs-switches.js',
        // COMPONENTS ===============================

         'dev-info/Goodis/M.A.J//HTML/js/functions.js',

        //  ===============================
        'src/**/js/**/*.js',
        'web/bundles/fosjsrouting/js/router.js'
    ])
        .pipe(uglify('master.min.js', {
            mangle: false,
            output: {
                beautify: false
            }
        }))
        .pipe(gulp.dest('./web/js'))
        .pipe (size());
});
```
possible or not.
Thank

**Comment by stof** [comment]
Well, Symfony does not have a strict requirement about the location of the JS. So it depends on your project.

Btw, commenting on the webpack-encore repo with a code snipped about Gulp is kind of funny...

**Comment by javiereguiluz** [comment]
@xorgxx yes, you can use Gulp with Symfony. I know developers who used it, but I don't know the exact details of making both work together.

However, after analysing the current state of JavaScript builders, we decided to use Webpack natively instead of Gulp. If you switch to Webpack, you'll be able to use Webpack Encore library and everything will be much simpler.

**Comment by Lyrkan** [comment]
I may be wrong but I think that he/she is already using Gulp and is asking how this snippet would translate to Encore.

If that's the case @xorgxx , I would say the answer is "not entirely possible".

By that I mean that gulp is only a task runner and what you are doing there is taking all your JS files, minifying them, and copying them into your destination folder.

What Webpack does is a bit more complex and you usually wouldn't just copy files. Instead you would declare entry points (each one of them being a single JS file from your project), and it would build a dependency graph and create the output files accordingly. This approach would require you to refactor your code in order to use JavaScript modules, which may be a lot of work depending on its current state.

**Comment by weaverryan** [comment]
I agree with @Lyrkan: "not entirely possible". If you're writing code that you all want included in one file like this, I would stick with Gulp.

When you use Webpack, it allows you to write code differently, where one JavaScript file can `require` another file... instead of you needing to make sure that certain JS files are loaded before other files for them to work (e.g. jQuery). You need to write your code a bit different, but it reduces the complexity and possibly of accidental breakage.

I would experiment a little bit with Webpack & Encore outside of your project to see how it works. You could then start using it little-by-little in your project. On KnpU, we have a tutorial about webpack (https://knpuniversity.com/screencast/javascript-webpack) including 2 chapters about handling legacy stuff. But, it will take some work to convert a big project into the new way of doing things :).

Cheers!
