### ISSUE TITLE
Why DefinePlugin is configured only in production?

### ISSUE THREAD

**Issue by dvc** [symfony/webpack-encore#171]
https://github.com/symfony/webpack-encore/blob/929a253f26b5b5875a1486f9c2d4552933ac947c/lib/plugins/define.js#L21

**Comment by stof** [comment]
hmm, we should probably always defined `process.env.NODE_ENV` indeed, but making the value `development` in dev.

**Comment by Lyrkan** [comment]
That's something I forgot to change when adding a way to configure the plugin.

Before that it was only used for the `process.env.NODE_ENV` constant so that check wasn't a big issue (even if, as you said @stof, we should probably define it in dev too), but now that there is a way to add new constants (using `Encore.configureDefinePlugin()`) the plugin has to be added all the time.
