### ISSUE TITLE
uglify now in webpack node_modules :( ?

### ISSUE THREAD

**Issue by wtorsi** [symfony/webpack-encore#208]
I don't know when it was introduced, but now webpack installs it's own uglifyjs-webpack-plugin in inner directory node_modules, and since this change 
`webpack-encore/lib/plugins/uglify.js`
uses UglifyJS which breaks babel transformations.

In my case it was `punc ()` error.
Deleting 
deleting webpack uglifyjs plugin from webpack node_modules directory do the trick.

Does somebody know other solutions?

**Comment by Lyrkan** [comment]
Hi @wtorsi,

I'm a bit confused about your issue, as far as I know Encore [has always used the uglifyJsPlugin](https://github.com/symfony/webpack-encore/blob/v0.0.1/lib/config_generator.js#L214) that comes up with Webpack.

In the previous versions of Webpack (< 3.0) it was [directly embedded in it](https://github.com/webpack/webpack/blob/v2.7.0/lib/optimize/UglifyJsPlugin.js) but since then the plugin [got its own repository](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) and is [now aliased](https://github.com/webpack/webpack/blob/v3.0.0/lib/optimize/UglifyJsPlugin.js), but that shouldn't cause any trouble.

Are you maybe trying to use a more recent version of `uglify-js-plugin` (such as the v1.0 that supports ES6 as a target)? If that's the case you'll have to remove the plugin added by Encore first before adding your own one (see https://github.com/symfony/webpack-encore/issues/139#issuecomment-323585179).

**Comment by wtorsi** [comment]
Hi, @Lyrkan 

Thank you, your answer was very helpful.
And yes, you are right uglifyjs-webpack-plugin is a dependency.

**Comment by ddproxy** [comment]
Haven't tried this in production yet, but to get dev to be happy I use the following...
```javascript
if (Encore.isProduction()) {
    config.plugins = config.plugins.filter(
        plugin => !(plugin instanceof webpack.optimize.UglifyJsPlugin)
);

    config.plugins.push(new UglifyJsPlugin());
}
```

**Comment by Lyrkan** [comment]
@wtorsi Closing this issue since the method above is likely the way to go for now if you want to use `uglify-es`. Feel free to reopen it if that didn't solve your problem!
