### ISSUE TITLE
Multiple SCSS / Ts in differents folders

### ISSUE THREAD

**Issue by zek0faws** [symfony/webpack-encore#240]
Hi,

I'm new to use webpack-encore, after reading carefully the documentation, and despite googling, I didn't find how to compile multiple scss/ts files in differents directories.

Here's my configuration : 

src
--Bundle1
----Resources
------public
--------js
----------test.js
----------acme.js
--------ts
----------bar.ts
----------foo.ts
--------scss
----------bar.scss
----------uknown.scss
--Bundle2
----Resources
------public
--------js
----------test.js
----------acme.js
--------ts
----------bar.ts
----------foo.ts
--------scss
----------bar.scss
----------uknown.scss

Here's my webpack.config.js : 

```
// webpack.config.js
var Encore = require('@symfony/webpack-encore');

Encore
// the project directory where all compiled assets will be stored
    .setOutputPath('public/build/')

    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')

    // will create public/build/app.js and public/build/app.css
    .addEntry('app', './src/Bundle/**/*')
    
// allow sass/scss files to be processed
    .enableSassLoader()


    // allow legacy applications to use $/jQuery as a global variable
    .autoProvidejQuery()

    .enableSourceMaps(!Encore.isProduction())

    // empty the outputPath dir before each build
    .cleanupOutputBeforeBuild()

    // show OS notifications when builds finish/fail
    .enableBuildNotifications()

// create hashed filenames (e.g. app.abc123.css)
// .enableVersioning()
;

// export the final configuration
module.exports = Encore.getWebpackConfig();
```

The addEntry is not working unfortunatelly and the enableSassLoader won't compile my scss files.

Maybe I'm doing something wrong ?

**Comment by vkryukov76** [comment]
You should generate a separate configuration for each of your bundles.

See #48 for information.

**Comment by Lyrkan** [comment]
Hey @zek0faws,

Indeed, `addEntry` won't work if you use it with a glob to select multiple files. We may actually add that feature in the future (see #188) but I'm not sure that's what you want to do there (especially since your glob would match all of your files).

When developing with Webpack you don't want to directly give it the list of all your files and ask it to generate a new file for each one of them (well, you could, but you'll miss many interesting features).

Instead you define entry points, usually targeting a single file each time, and let Webpack build a dependency graph.

For instance if you have the following files:

```
|- page1.js
|- page2.js
`- modules
    |- module1.js
    |- module2.js
    `- module3.js
```

What you would do is call `addEntry()` twice: one time for `page1.js` and another one for `page2.js`.
Then, if `page1.js` requires `module1.js` and `module2.js`, Webpack will automatically include them in the resulting file and use them when needed. That also works if `module1.js` and/or `module2.js` need `module3.js`. After running Encore you'll only get two output files to include in your different pages.

For your (S)CSS files, you can do the same thing, but using `addStyleEntry()` instead (`addEntry()` would actually also work but you'll end-up with some extra files). So you can create for instance an `index.scss` file and import other SCSS file inside of it (using the `@import` directive).

**Comment by zek0faws** [comment]
Hi @Lyrkan,

Thank you for your developped answer.

Now I really can get how webpack should works. My configuration is now nice.
And for my TS files I'm using ts-loader, like the documention said.

Thank you ! :)
