### ISSUE TITLE
Exception thrown during build process

### ISSUE THREAD

**Issue by zmitic** [symfony/webpack-encore#280]
I still don't have CI that would resolve this but I think there is a problem with accessing manifest.json file. While ``yarn run encore production`` is executing (sometimes pretty long), site is throwing this exception:

```
Uncaught PHP Exception Twig_Error_Runtime: 
"An exception has been thrown during the rendering of a template 
("Asset manifest file "/var/www/php/public/build/manifest.json" does not exist.")
```

This makes me think that each request is parsing manifest.json file instead of keeping it in container. Shouldn't its values be kept compiled once to avoid performance hits and downtime?

Just in case I am wrong, this is my installation script:

```
yarn run encore production
rm -rf var/cache/prod
composer dump-autoload --optimize --no-dev --classmap-authoritative
./bin/console cache:warmup
./bin/console assets:install
./bin/console doctrine:schema:update --force
service php7.2-fpm restart
```

opcache validation is turned off so if values of manifest file are in php, there shouldn't be downtime at all.

**Comment by Lyrkan** [comment]
Hi @zmitic,

Since Encore only generates that `manifest.json` file which is then read by the [Asset component](https://github.com/symfony/asset/blob/master/VersionStrategy/JsonManifestVersionStrategy.php) that issue should probably opened in the following repository: https://github.com/symfony/symfony/

I'm not sure that reading it everytime is a big issue though (in terms of performance), and because you probably won't build your JS/CSS directly on your production servers you shouldn't encounter that error unless something went wrong during your packaging process.

**Comment by zmitic** [comment]
Ok, thanks. I missed in the docs that I should build them locally first.

**Comment by Lyrkan** [comment]
Well, you could do it remotely but the `manifest.json` file won't be the only issue in this case:

* if you called `cleanupOutputBeforeBuild()` (which is recommended) your assets won't be available during the build
* you'll have to install all your build dependencies (node, webpack, ...) on your production servers

Building your assets beforehand and packaging the whole thing is probably the easiest way to deal with all of that ^^
