### ISSUE TITLE
Fonts and Images Still Versioned when Versioning DIsabled

### ISSUE THREAD

**Issue by pdugas** [symfony/webpack-encore#282]
Not sure if this is by design or I'm missing something.  I had enableVersioning() removed from my webpack.config.js file and the generated js and css files no longer have the hash inserted in their filenames but the files down in the images and configs subdirectories are still versioned. I need to disable versioning to share a custom icon font with a front-end app that I've not yet separated out of my project.

**Comment by Lyrkan** [comment]
Hi @pdugas,

It is indeed by design, we've made this change in #110 because not adding the hash would lead to a more annoying issue: if you had two files with the same names in different subfolders only one of them would end-up in the  build folder.

The others fixes we could have implemented are explained in the PR but at the time adding a hash seemed to be the right choice (even though there is now another small thing to fix... see #246).

Since then another issue (#136) was opened by someone who felt it wasn't the right thing to do, feel free to chime in if you want to share your thoughts!

That being said, you don't have to disable versioning entirely in your case, there is a `configureFilenames` method that allows you to override how images/fonts are named: https://github.com/symfony/webpack-encore/blob/ccbae35a7f8dc34467493cba84233e88838f0024/index.js#L746-L767

**Comment by pdugas** [comment]
I had just found configureFilenames() about a minute before your response. Should work fine for me. Thanks so much for the effort.
