### ISSUE TITLE
How to set the NODE_PATH environment variable

### ISSUE THREAD

**Issue by Aerendir** [symfony/webpack-encore#297]
I've tried to set in the `.env` file the environment variable `NODE_PATH` but it seems not working.

Any ideas about why? Is an error of mine or is something else?

Or maybe I can set the path using `resolve.modules.pathResolve` as suggested here: https://github.com/webpack/webpack/issues/2676#issuecomment-227383311

Is it possible?

**Comment by weaverryan** [comment]
Hey there!

So, the .env is only loaded when Symfony boots up - so Encore doesn’t touch that file at all. But basically, since you’re running Encore from the command line, you should just set the NODE_PATH env var yourself right before calling Encore. Or better yet, do it all in one command:

NODE_PATH=/foo/path yarn run encore dev

I hope that helps :).
