### ISSUE TITLE
Webpack Connection Refused For Images

### ISSUE THREAD

**Issue by yusufilkeroguz** [symfony/webpack-encore#303]
Hi,
My assets folder:
![screenshot from 2018-04-16 18-55-46](https://user-images.githubusercontent.com/3788174/38821573-92d00856-41a9-11e8-99ab-baa625d339b2.png)

After "webpack" command:
![screenshot from 2018-04-16 19-11-17](https://user-images.githubusercontent.com/3788174/38821709-f52f9246-41a9-11e8-919b-23bce88ba65a.png)

But connection refusing when i try to open image:

![image](https://user-images.githubusercontent.com/3788174/38822089-14263bea-41ab-11e8-92d5-32d759084b4e.png)

I tried to disable image loader but got error:
```
 @ ./node_modules/css-loader??ref--3-2!./node_modules/resolve-url-loader??ref--3-3!./node_modules/sass-loader/lib/loader.js??ref--3-4!./assets/sass/main.scss 7:160132-160176
 @ ./assets/sass/main.scss

 error  in ./assets/img/profile-borders/gold.png

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

My Webpack Conf:
```
Encore
    .configureRuntimeEnvironment('dev-server')
    .setOutputPath('./public/build/')
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .addEntry('js/app', './assets/js/index.js')
    .addStyleEntry('css/app', './assets/sass/index.scss')
    .enableSassLoader()
    .autoProvidejQuery()
```

Node Version: 9.7.1
Sass: 3.5.5

**Comment by yusufilkeroguz** [comment]
Note: Worked "Encore.configureRuntimeEnvironment('production')"

**Comment by weaverryan** [comment]
Hi there!

Instead of calling configureRuntimeEnvironment() (which is only for very advanced setups), you should delete this line and choose whether ou want the dev-server or a production build when running the command:

./node_modules/.bin/encore dev-server
./node_modules/.bin/encore production 

Check the docs for more details - these commands are shown there. Don’t use configureRuntimeEnvironment in place of that :).

Cheers!
