### ISSUE TITLE
Strange problem about loading some fonts

### ISSUE THREAD

**Issue by lebadapetru** [symfony/webpack-encore#310]
I'm using webpack-encore(the latest release) with symfony 4 and i got the following errors regarding some fonts for a package called simple-line-icons:

GET http://localhost/build/fonts/Simple-Line-Icons.0cb0b9c5.woff2 net::ERR_ABORTED
GET http://localhost/build/fonts/Simple-Line-Icons.d2285965.ttf net::ERR_ABORTED
GET http://localhost/build/fonts/Simple-Line-Icons.78f07e2c.woff net::ERR_ABORTED

The thing is that the path is wrong,it should be: 

http://localhost/my-project/public/build/fonts/Simple-Line-Icons.0cb0b9c5.woff2

I don't know for sure what is wrong,it may be something silly since i'm new with this kind of tools,but i hope you can help me out.

Here's how my webpack.config.js looks like:

```
var Encore = require('@symfony/webpack-encore');

Encore
    // the project directory where compiled assets will be stored
    .setOutputPath('public/build/')
    // the public path used by the web server to access the previous directory
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    // uncomment to create hashed filenames (e.g. app.abc123.css)
     .enableVersioning(Encore.isProduction())

    // uncomment to define the assets of the project
     .addEntry('js/app', './assets/js/app.js')
     //.addEntry('images/image', './assets/images/lightspeed.png') TODO according to a post on github, addImagesEntry is on working...
     .addStyleEntry('css/app', './assets/css/app.scss')

    // uncomment if you use Sass/SCSS files
     .enableSassLoader()

    // uncomment for legacy applications that require $/jQuery as a global variable
     .autoProvidejQuery()
;

module.exports = Encore.getWebpackConfig();

```

The strange thing is that in my main app.scss i got those lines:

```
@import '~bootstrap/scss/bootstrap';
@import "~font-awesome/scss/font-awesome";
@import "~flag-icon-css/sass/flag-icon";
@import "~simple-line-icons/scss/simple-line-icons";
```

Yet only the last one messes the font paths... even though there are all the same in my manifest.json:

```
{
  "build/css/app.css": "/build/css/app.css",
  "build/fonts/Simple-Line-Icons.eot": "/build/fonts/Simple-Line-Icons.f33df365.eot",
  "build/fonts/Simple-Line-Icons.ttf": "/build/fonts/Simple-Line-Icons.d2285965.ttf",
  "build/fonts/Simple-Line-Icons.woff": "/build/fonts/Simple-Line-Icons.78f07e2c.woff",
  "build/fonts/Simple-Line-Icons.woff2": "/build/fonts/Simple-Line-Icons.0cb0b9c5.woff2",
  "build/fonts/fontawesome-webfont.eot": "/build/fonts/fontawesome-webfont.674f50d2.eot",
  "build/fonts/fontawesome-webfont.ttf": "/build/fonts/fontawesome-webfont.b06871f2.ttf",
  "build/fonts/fontawesome-webfont.woff": "/build/fonts/fontawesome-webfont.fee66e71.woff",
  "build/fonts/fontawesome-webfont.woff2": "/build/fonts/fontawesome-webfont.af7ae505.woff2",
  "build/images/fontawesome-webfont.svg": "/build/images/fontawesome-webfont.912ec66d.svg",
  "build/js/app.js": "/build/js/app.js"
}
```

**Comment by Lyrkan** [comment]
Hi @lebadapetru,

Could you run `yarn encore dev` and look for the `@font-face` declarations in the generated `app.css` file (it shouldn't use the `manifest.json` file in this case)?

I'm a bit surprised that it works for your other fonts since, if I'm not wrong, all of them should contain things like `src: url(/build/fonts/....)`, and not work if your app is in a subdirectory.

When your app lives under a subdirectory you have to include the whole path when calling `setPublicPath()` (see [that part of the documentation](https://symfony.com/doc/current/frontend/encore/faq.html#my-app-lives-under-a-subdirectory)).

**Comment by lebadapetru** [comment]
Hi @Lyrkan,

Sorry for the late response, here are the requested lines:


@font-face {
  font-family: "simple-line-icons";
  src: url(/build/fonts/Simple-Line-Icons.f33df365.eot);
  src: url(/build/fonts/Simple-Line-Icons.f33df365.eot) format("embedded-opentype"), url(/build/fonts/Simple-Line-Icons.0cb0b9c5.woff2) format("woff2"), url(/build/fonts/Simple-Line-Icons.d2285965.ttf) format("truetype"), url(/build/fonts/Simple-Line-Icons.78f07e2c.woff) format("woff"), url(/build/images/Simple-Line-Icons.2fe2efe6.svg) format("svg");
  font-weight: normal;
  font-style: normal;
}

And why are you saying they shouldn't work? Isn't that a relative path? So if i'm calling the fonts with the current url like localhost/my-project/public it should look for those fonts with my current url + the url of the fonts,ain't it? 

Anyway,i added the subfolder and still had the same problem,but if i specify the full path it works .setPublicPath('/my-project/public/build')

This thing may be because of my xampp? On production i suppose i'll have to specify just the subfolder...

**Comment by Lyrkan** [comment]
Hey @lebadapetru,

> Sorry for the late response, here are the requested lines:

So yeah, for that font it's normal that it doesn't work if your app is located in a subdirectory.

> And why are you saying they shouldn't work? Isn't that a relative path?

Nope, this isn't a relative path. If it starts with a slash (that's the case here) it is an absolute path and it will be added directly after the hostname (that's why it tries to load http://localhost/build/fonts/Simple-Line-Icons.0cb0b9c5.woff2).

And what I meant by "they shouldn't work" is that you probably have the same kind of `@font-face` declaration for font-awesome, so that one shouldn't work either.

> This thing may be because of my xampp? On production i suppose i'll have to specify just the subfolder...

Yeah, if you use the default conf your Apache probably serves all files from a single directory so you had to create a `my-project` folder in it. Usually what you'd is [configure what's called a vhost](https://symfony.com/doc/current/setup/web_server_configuration.html#apache-with-mod-php-php-cgi) and point it directly to the "public" folder. In that case a path starting by "/build" would work.

**Comment by lebadapetru** [comment]
Alright,thanks a lot and sorry for my lack of knowledge,i still have a lot to learn.
