### ISSUE TITLE
require() is not compliled in the order I set them

### ISSUE THREAD

**Issue by etshy** [symfony/webpack-encore#312]
Hi, I have a js file that reuire others files
```
require('../vendor/jquery-ui/jquery-ui.min');

require('./img-scramble');

require('./file-upload-dropzone');
```
In the `img-scramble` file I have a js class
And in `file-upload-dropzone` I want to use this class.

But the compilation put the files with the class is put after my other file, and it's undefined when I try to use it.

```
Uncaught ReferenceError: Scramble is not defined
    at HTMLDocument.<anonymous> (file-upload-dropzone.js:258)
    at mightThrow (jquery.js:3534)
    at process (jquery.js:3602)
```
The thing is, in the compiled file, my js is the first file loaded, before Dropzone, that I use in the page, and Dropzon still works.
So I don't really know why it doesn't work for my Class

edit: I define my class with the `class` word
and I call it with `new Class()`

**Comment by weaverryan** [comment]
Hey @etshy!

This issue is that you should be *exporting* values from your modules, instead of relying on them to set some global variables. Because, yea, as strange as it sounds (and you don't hit it very often), Webpack does *not* always guarantee ordering.

So, your setup should look something like this:

```diff
// img-scramble.js

class Scramble
{
}

+ // this is the key: you export a value from this file
+ module.exports = Scramble.
```

Then, you can import this from any other file. Because you need it in `file-upload-dropzone.js`, I would import it there:

```diff
// file-upload-dropzone.js

// this will be set to the value(class) you exported
const Scramble = require('./img-scramble');
```

This is really the best part of using Webpack: you explicitly export values from a file and import them when you need it :).

Cheers!
