### ISSUE TITLE
Cannot extract bootstrap sass

### ISSUE THREAD

**Issue by danielrolland** [symfony/webpack-encore#345]
Hi !
I'm using Encore for a project in which I use lots of @include in every different page, so I'd like to extract bootstrap in order to keep my css's light. I've done it as mentionned in the documentation : 
```
.createSharedEntry('vendor', [
        'jquery',
        'bootstrap',
        // you can also extract CSS - this will create a 'vendor.css' file
        // this CSS will *not* be included in page1.css or page2.css anymore
        'bootstrap/scss/bootstrap.scss'
    ])
```
then in my global.scss (which includes custom variables for colors, etc.) i'm importing bootstrap, again as mentionned in the documentation : 
`@import '~bootstrap/scss/bootstrap.scss';`
an then I import my global.scss file in other .scss files so they have access to bootstrap as well as my global custom variables, like this : 
```
// asset .../homepage.scss
@import "global";
```

However I keep getting the full bootstrap.css file included in every css file ! I must be doing something wrong, but I don't see why since I'm implementing it as in the documentation. Could anyone help me figuring it out ? Thanks a lot !

**Comment by stof** [comment]
I don't think webpack is able to avoid including some of the sass output. If you want to access only the bootstrap variables and mixins in your own sass files, you should include only these parts of Bootstrap, and not all files rendering styles.

**Comment by weaverryan** [comment]
Indeed. It *should* work the way you're expecting - I'm a little surprised that it's not actually :/. But yes, the CSS support for this "shared entry" stuff in Webpack I know isn't 100% as good as for JavaScript code. It may be what stof mentioned. Or, it may be because you are using `@import` in CSS (and it would instead work if you were "requiring" the SASS files from JavaScript... but then you wouldn't have access to the Bootstrap variables in your CSS).

If this isn't working the way it should, unfortunately, it's probably not something we can fix. BUT, two things:

1) As stof mentioned, the workaround would be to separate your variables from the rest of your SASS so that you can *only* require some file like `variables.scss` in the locations when you only want the variables.

2) In the next version of Encore (that will use Webpack 4), we will have a new feature called `Encore. splitEntryChunks()` that will *likely* do what you want correctly. Basically, Webpack 4 rewrote some things internally to be a lot smarter about avoiding "chunk" duplication. This new feature leverages that. So, in the coming weeks, watch for the next release and this feature :).

Cheers!
