### ISSUE TITLE
enableSassLoader ignore callback options

### ISSUE THREAD

**Issue by djmetla** [symfony/webpack-encore#357]
Hey,

i use WebPack Encore for compile assets scss. I cant compress output .css file. 

I use this code for compress output .css
`.enableSassLoader(function(options) { 
options.outputStyle = "compressed"
})`

and no working. Any tip how to compile .scss with outputstyle compressed in webpack-encore? 

Ty lot :)

**Comment by Lyrkan** [comment]
Hi @djmetla,

Which version of Encore are you using?
Scss files should be automatically minified in production mode without any additional configuration.

We've a test case there for CSS files but since Scss handling just adds an extra layer both should give the same result:

https://github.com/symfony/webpack-encore/blob/c247131aa8ec4a4c1582fd3e862539461113402a/test/functional.js#L821-L825

**Comment by jrobeson** [comment]
so does `precision` not work either then @djmetla ?

**Comment by weaverryan** [comment]
Closing - issue is old. Please open a new issue if needed! Thanks!
