### ISSUE TITLE
Wrong manifest.json while parallel build

### ISSUE THREAD

**Issue by Fatal1stZ** [symfony/webpack-encore#374]
When i'm buidling encore in a parallel mode, a manifest.json file generates only with assets of last bundle.

Is this correct?
I think, it should return manifest.json with all bundle assets, used in build.
```js

      getDirectories( BUNDLES_PATH ).forEach( source => {

        let entries = [ "babel-polyfill" ]
        if ( isEndpointExists( source ) ) entries.push( resolveEntrypoint( source.dir ) )
        if ( isScssExists( source ) ) entries.push( resolveScss( source.dir ) )

        Encore
          .setOutputPath( "web/bundles/" )
          .setPublicPath( isProduction ? publicPath : "/bsp/bundles" )
          .setManifestKeyPrefix( "bundles" )
          .enableSourceMaps( true )
          .enableVersioning( isProduction )
          .enableSassLoader()
          .enableReactPreset()
          .addEntry( source.name + "/main", entries )

        const webpackConfig = Encore.getWebpackConfig()
        webpackConfig.name = source.name

        webpackConfigs.push( webpackConfig )
        Encore.reset()
      } )

      return webpackConfigs
  }
```

**Comment by Lyrkan** [comment]
Hello @Fatal1stZ,

I understand what you're trying to achieve but I'm not sure that there's an issue with Encore/Webpack.

What you call "parallel mode" is nothing more than multiple Webpack configurations built at the same time, they don't really share data with eachothers. If one of these builds writes into the same file (not only the `manifest.json`) than another one, you'll lose the previous content.

Usually that's not an issue because you would have a different target/output path (see [this example](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations) for instance) for all the configurations... but in your case all the builds share the same output path, so all of them write their own `manifest.json` in it and the slowest one "wins".

You could either:
* use a single configuration with multiple calls to `.addEntry()` (which will be slower but will also avoid a lot of potential issues and allow you to use things like shared entries and `cleanupOutputBeforeBuild()`)
* use a different `outputPath` for all your configurations and merge the `manifest.json` files manually

**Comment by Fatal1stZ** [comment]
I like second option, but when should i merge manifest manually?
Is there any hook fot this? For example, when lastest (or every) bundle is build and manifest is ready?

**Comment by Lyrkan** [comment]
Hm... maybe you could create a small Webpack plugin that listens to the [`done` hook](https://webpack.js.org/api/compiler-hooks/#done). But you'll have to add it to all your configs and it'll be called for each one of them.

Another way to do it if you don't use the `watch` feature of Webpack would be to create a small script that merges all the manifests and call it after Encore in a npm script.

**Comment by Fatal1stZ** [comment]
I've made it another way.. 
Configured manifest plugin as 
`.configureManifestPlugin options => options.fileName = "${name}/manifest.json")`
and configured Symfony assets section in parameters.yml:
```
framework:
    assets:
        packages:
            admin:
                json_manifest_path: "%kernel.project_dir%/web/bundles/admin/manifest.json"
            user:
                json_manifest_path: "%kernel.project_dir%/web/bundles/user/manifest.json"
```

**Comment by Fatal1stZ** [comment]
I got overwriting common manifest.json aswell (in generate callback), but this option doesn't seem to be good anymore.
