### ISSUE TITLE
Passing multiple configs into --config-name

### ISSUE THREAD

**Issue by Fatal1stZ** [symfony/webpack-encore#378]
Is there any way to pass more then one value into --config-name parameter?
For example if i want to load only 2 webpack configs of 10 in dev mode.

**Comment by Lyrkan** [comment]
Hi @Fatal1stZ,

That question is probably more related to Webpack than Encore but AFAIK [`--config-name` only supports a single name](https://github.com/webpack/webpack-cli/blob/d26ea82564efd740f48c3cc1ed61ed56eb3f3cb3/bin/config-yargs.js#L33-L38).

But you could probably change your `webpack.config.js` file to make it look into an environment variable (since Webpack doesn't like unknown arguments) and only generate the configs that are referenced in it.

**Comment by Fatal1stZ** [comment]
Yeah i did it like env variable configs, that is waiting for some config names divided by space.
Thank you.
