### ISSUE TITLE
Could not find package webpack-encore - Windows 7

### ISSUE THREAD

**Issue by DarckCrystale** [symfony/webpack-encore#386]
**OS:** Windows 7
**Symfony version:** `3.4.15`
**Composer version:** `1.7.2`

I use Git Bash for Windows as a terminal.

I try to follow the instructions from the official documentation https://symfony.com/doc/3.4/frontend/encore/installation.html

> First, make sure you install Node.js and also the Yarn package manager. Then run:
> 
>     composer require webpack-encore
>     yarn install

But `composer require webpack-encore` throws an error:

>     [InvalidArgumentException]
>     Could not find package webpack-encore.
>     
>     Did you mean one of these?
>           symfony/webpack-encore-pack
>           rebolon/symfony-skeleton
>           knpuniversity/webpack-encore-bundle

**Comment by Lyrkan** [comment]
Hi @DarckCrystale,

Are you using [Flex](https://symfony.com/doc/current/setup/flex.html)?

If that's not the case you're getting this error because `webpack-encore` is not really a composer package, but an alias for the `symfony/webpack-encore-pack` recipe (see https://symfony.sh/).

To set-up Encore without Flex you can follow [these instructions](https://symfony.com/doc/3.4/frontend/encore/installation-no-flex.html) instead.

**Comment by DarckCrystale** [comment]
Thank you, it solved my problem! :blue_heart:
