### ISSUE TITLE
error while compiling 

### ISSUE THREAD

**Issue by SeanEmadri** [symfony/webpack-encore#391]
ERROR in ./resources/assets/js/components/ExampleComponent.vue
vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config

**Comment by mmarton** [comment]
https://symfony.com/doc/current/frontend/encore/vuejs.html

**Comment by Lyrkan** [comment]
Hi @SeanEmadri,

To explain a bit more why this doesn't work: there is an incompatibility between the versions of the vue-loader and of Encore that you are using.

The last released version of Encore only supports `vue-loader` up to version 14, which is why you have to run the following command to prevent yarn (or npm) from installing a newer one:

```
yarn add --dev vue vue-loader@^14 vue-template-compiler
```
