### ISSUE TITLE
Deploying on server where npm is not in "/usr/bin/env: node"

### ISSUE THREAD

**Issue by picks44** [symfony/webpack-encore#405]
Hi,

I'm deploying my Symfony app on a server where npm is not reachable in `/usr/bin/env` but in something like `/opt/alt/alt-nodejs8/root/usr/bin/npm`.

I've adapted my commands to `/opt/alt/alt-nodejs8/root/usr/bin/npm install` and then I got the following error 
`npm WARN lifecycle npm is using /opt/alt/alt-nodejs8/root/usr/bin/node but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.`

So I updated my command again to `/opt/alt/alt-nodejs8/root/usr/bin/npm install --scripts-prepend-node-path=true` which worked well but now after firing the command `/opt/alt/alt-nodejs8/root/usr/bin/npm run encore production --scripts-prepend-node-path=true` I got the following error

```
 > @ encore /home/etaspqdw/public_html/releases/34
 > encore "production"
  Running webpack ...
   ERROR  Failed to compile with 2 errors4:59:30 PM
   error
  Entry module not found: Error: Can't resolve 'babel-loader' in '/home/etaspqdw/public_html/releases/34'
   error
  Entry module not found: Error: Can't resolve 'babel-loader' in '/home/etaspqdw/public_html/releases/34'

```

Why do I need "babel-loader" and how can I fix this?

I'm running this locally without any error...

**Comment by Lyrkan** [comment]
Hi @picks44,

`babel-loader` is a [Webpack loader](https://webpack.js.org/loaders/) that handles JavaScript files. It mostly allows you to write "modern" code and then transpile it so it works on older browsers.

It should have been installed with Encore (during the `npm install`), so I'm not sure why webpack doesn't find it.

Could try the following command?

```shell
$ /opt/alt/alt-nodejs8/root/usr/bin/node ./node_modules/.bin/encore production
```

Also, is that on the server that'll also host your app? I ask that because usually people run the whole build process *before* deploying. This would solve your issue since you wouldn't even need to have `node`/`npm` installed on that server (unless you use them for something else).

**Comment by picks44** [comment]
Yes I thought so, I deleted to `node_modules` folder to install everything again but it happened again...

```
[etaspqdw@world-324 current]$ /opt/alt/alt-nodejs8/root/usr/bin/npm install --sc                                                                                                                                                             ripts-prepend-node-path=true

> node-sass@4.9.3 install /home/etaspqdw/public_html/releases/34/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/etaspqdw/.npm/node-sass/4.9.3/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/etaspqdw/public_html/releases/34/node_modules/@symfony/webpack-encore/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.9.3 postinstall /home/etaspqdw/public_html/releases/34/node_modules/node-sass
> node scripts/build.js

Binary found at /home/etaspqdw/public_html/shared/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine
npm WARN 34 No repository field.
npm WARN 34 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@symfony/webpack-encore/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1076 packages in 44.303s
```

Then

```
[etaspqdw@world-324 current]$ /opt/alt/alt-nodejs8/root/usr/bin/node ./node_modules/.bin/encore production
Running webpack ...

 ERROR  Failed to compile with 2 errors                                                                                                                                                                                            8:20:46 PM

 error

Entry module not found: Error: Can't resolve 'babel-loader' in '/home/etaspqdw/public_html/releases/34'

 error

Entry module not found: Error: Can't resolve 'babel-loader' in '/home/etaspqdw/public_html/releases/34'

```

**Comment by picks44** [comment]
I just checked my local `node_modules` folder and found 745 folder in it, and my deployed folder only has 11 !!
Id there a reason for this ? 
My `package.json` is the following
```
{
  "devDependencies": {
    "@fortawesome/fontawesome-free": "^5.3.1",
    "@symfony/webpack-encore": "^0.20.1",
    "bootstrap": "^4.1.3",
    "isotope-layout": "^3.0.6",
    "jquery": "^3.3.1",
    "jquery-bridget": "^2.0.1",
    "node-sass": "^4.9.3",
    "popper.js": "^1.14.4",
    "sass-loader": "^7.1.0",
    "webpack-notifier": "^1.6.0"
  },
  "scripts": {
    "encore": "encore"
  }
}
```

**Comment by Lyrkan** [comment]
Which version of npm are you using?

**Comment by picks44** [comment]
> Which version of npm are you using?

[etaspqdw@world-324 ~]$ /opt/alt/alt-nodejs8/root/usr/bin/node -v
v8.11.3

**Comment by Lyrkan** [comment]
I was asking about npm (the package manager), not node.

Based on your logs it seems that everything is installed the npm 2 way (see http://npm.github.io/how-npm-works-docs/npm2/how-npm2-works.html).

For instance, in your dev environment you'll probably have a `node_modules/uglifyjs-webpack-plugin` folder, whereas on that server it'll be in `node_modules/@symfony/webpack-encore/node_modules/uglifyjs-webpack-plugin`.

Normally, since npm 3 (http://npm.github.io/how-npm-works-docs/npm3/how-npm3-works.html) it only uses that kind of tree when two different versions of a given dependency must be installed at the same time, which should not be the case here.

**Comment by Lyrkan** [comment]
That's very odd... do you have a `package-lock.json` file? If no, could you try adding one, created from your dev environment (it should be automatically generated by `npm`)?

Then, on your server, run `npm ci` instead of `npm install`. It should install dependencies based on what's inside the lock file, including the dependency tree.

**Comment by Lyrkan** [comment]
Erm, nevermind... I just noticed that `npm ci` was added in npm 5.7.0... so you won't be able to use it unless you update npm on your server.

**Comment by picks44** [comment]
I've asked for a npm update to see if it fixes things.

**Comment by picks44** [comment]
ANd it did! Using npm 6.4.1

**Comment by Lyrkan** [comment]
Glad to hear it :)
