### ISSUE TITLE
resolve-url-loader magic behavior

### ISSUE THREAD

**Issue by madwizard-thomas** [symfony/webpack-encore#428]
When using encore for a project I was surprised to have the relative url(...) image references in my sass files resolved correctly even though the relative path were wrong (I moved the sass files but not the images). 

Turns out that the resolve-url-loader package will pretty much search your whole project directory for the image filenames and use anything that matches (starting with the correct relative path but if it does not resolve it will widen the search until it finds package.json and then do a recursive file search).

This is not only slow but also confusing and promotes the (accidental) use of erroneous paths in CSS files. The author of resolve-url-loader also [acknowledges](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader-filesearch/README.md) this: 

> The file-search "magic" was always a hack and solved problems back in the days when .css was distributed by Bower. Back then it was common for packages to be broken.
> Now days bundling CSS is common place and broken packages are quickly fixed. It should be possible to solve your use-case without a full file search.
> The author recommends you use the join option in resolve-url-loader@>=3.0.0 to make a more targeted fix.

Would you consider upgrading the resolve-url-loader dependency to ^3.0?

**Comment by pscheit** [comment]
and resolve-url-loader in 3.0.0 uses postcss per default - which is more stable than the old parsing engine

**Comment by Lyrkan** [comment]
Chiming in since it can also cause some slowdowns (see #534).

We can update `resolve-url-loader` but we'll have to make sure that the [breaking changes introduced in v3](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/README.md#version-3) don't affect too many builds...

**Comment by stof** [comment]
Well, the main BC break in v3 is that the magic search is gone.

**Comment by Lyrkan** [comment]
Which could already be annoying for some people if they added Encore to a legacy project, but I guess the current version is stable enough so they could stay on that one without any issue.

That being said, the change that I'm a bit more worried about is the `root` option not meaning the same thing than before and having to be set in *some* cases only. I haven't looked into it in details yet so maybe that's not really a problem.

**Comment by Lyrkan** [comment]
I did some quick tests and I suspect that there are other breaking changes than the ones listed in the page linked in my previous comment...

After updating, all of our tests using the following file fail (see [here](https://travis-ci.org/Lyrkan/webpack-encore/jobs/503299595#L795)):

https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/fixtures/css/background_image.scss#L1-L3

And I can't see any reason why it would need the magic search for that one...

It may be related to how we run our tests but I've got no real lead so far apart from the fact that [at that point](https://github.com/bholloway/resolve-url-loader/blob/ec651ca0abb64fcfc6832b31bd0dada8088829a2/packages/resolve-url-loader/lib/join-function.js#L90-L99) `element` contains a relative path (`test_tmp/<id>/images/symfony_logo.png`) instead of an absolute one.

**Comment by madwizard-thomas** [comment]
It seems like resolve-url-loader's postcss plugin (lib/engine/postcss.js) determines the `baseOrIteratorOrAbsent` parameter for that function from the original filename from the source map, which leads to a relative url `test_tmp/<id>/...`. Might be an issue with resolve-url-loader?

**Comment by Lyrkan** [comment]
I think I found out where the issue comes from (long explanation ahead :)).

For those failing tests, the `resolve-url-loader` receives a source map that looks like the following:

```js
{
  version: 3,
  sourceRoot: '/path/to/webpack-encore',
  sources: ['test_tmp/eqlml/css/background_image.scss'],
  sourcesContent: ['h2 {\n  background: top left url(\'./../images/symfony_logo.png\') no-repeat;\n}\n'],
  names: [],
  mappings: 'AAAA,AAAA,EAAE,CAAC;EACD,UAAU,EAAE,GAAG,CAAC,IAAI,CAAC,mCAAmC,CAAC,SAAS,GACnE' 
}
```

What's important there is that, even though we are running Webpack from `/path/to/webpack-encore` (that's what `process.cwd()` would return), our test cases are in their own folder, in this case `test_tmp/eqlml` (so the Webpack context is `/path/to/webpack-encore`).

The `resolve-url-loader` then uses a function of the `adjust-sourcemap-loader` that is supposed to change the elements of `sources` into absolute paths.

What is expected:

```js
{
  version: 3,
  sourceRoot: undefined,
  sources: ['/path/to/webpack-encore/test_tmp/la26hu/css/background_image.scss'],
  sourcesContent: ['h2 {\n  background: top left url(\'./../images/symfony_logo.png\') no-repeat;\n}\n'],
  names: [],
  mappings: 'AAAA,AAAA,EAAE,CAAC;EACD,UAAU,EAAE,GAAG,CAAC,IAAI,CAAC,mCAAmC,CAAC,SAAS,GACnE'
}
```

What happens in reality:

```js
{
  version: 3,
  sourceRoot: undefined,
  sources: ['test_tmp/84c93/css/background_image.scss' ],
  sourcesContent: ['h2 {\n  background: top left url(\'./../images/symfony_logo.png\') no-repeat;\n}\n'],
  names: [],
  mappings: 'AAAA,AAAA,EAAE,CAAC;EACD,UAAU,EAAE,GAAG,CAAC,IAAI,CAAC,mCAAmC,CAAC,SAAS,GACnE'
}
```

And since the resulting path isn't an absolute one the rest of the process doesn't work correctly as previously noted.

But why does the source map transformation fails?

Welp, it turns out that the `adjust-sourcemap-loader` works by trying various strategies (called "codecs") to generate those absolute paths and returning the first one that works.

Because the `sourceRoot` of our first source map is the project root the codec we are expecting that loader to use is the [`project-relative`](https://github.com/bholloway/adjust-sourcemap-loader/blob/master/codec/project-relative.js) one.

To determine the "base path" that will be joined to all the paths from the `sources` array it [calls a `getContextDirectory()`](https://github.com/bholloway/adjust-sourcemap-loader/blob/b5781ceed0a5f7287a081ddaa28de455d05262cf/codec/project-relative.js#L29) function that should return `/path/to/webpack-encore` but returns `/path/to/webpack-encore/test_tmp/eqlml` instead. Since `/path/to/webpack-encore/test_tmp/eqlml/test_tmp/eqlml/css/background_image.scss` doesn't exist the codec is deemed invalid.

The reason `getContextDirectory()` returns the wrong path is that [at this point](https://github.com/bholloway/adjust-sourcemap-loader/blob/b5781ceed0a5f7287a081ddaa28de455d05262cf/codec/utility/get-context-directory.js#L14), `this.options.context` is set to `/path/to/webpack-encore/test_tmp/eqlml`, which is caused by... the `LoaderOptionsPlugin`!

https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/lib/plugins/loader-options.js#L31-L44

I'm not sure that there is a valid reason to use that plugin anymore since it was made to facilitate migrations from Webpack 1 to Webpack 2... by now the vast majority of loaders have probably been updated and it could cause other similar issues due to the way it works.
