### ISSUE TITLE
Change output path from command line

### ISSUE THREAD

**Issue by fmarchalemisys** [symfony/webpack-encore#447]
I need to change the output directory where packaged files are written when encore is run on the command line. I tried this:

    yarn encore dev --silent --output-path="public/build-dev/"

But encore keeps writing the `entrypoints.json` file to the output path defined in webpack.config.js:

    639 files written to public/build

The idea is to write the dev configuration in `public/build-dev` with a symlink from `public/build` to `public/build-dev`. As the dev configuration completes in 20 seconds or so, the web site is quickly available. Then I start the production configuration and write it to `public/build-prod`. It takes around 15 minutes to complete then I switch the `public/build` symlink from `public/build-dev` to `public/build-prod` and the site is ready to serve optimized files.

To achieve this, I need to convince encore to write the `entrypoints.json` file to the same directory as specified on the command line. How can I do this?

**Comment by Lyrkan** [comment]
Hi @fmarchalemisys,

Is there something that prevents you from doing that using [`Encore.setOutputPath(...)`](https://github.com/symfony/webpack-encore/blob/bbf687bc56dccf528e37a913c89356188b986551/index.js#L61-L74)?

Anyway, if I understand correctly you are trying to serve a dev build in production while the prod build is compiling? If that's the case I wouldn't recommend it for various reasons... it would probably be better to create the production build *before* uploading it to your server.

**Comment by msheakoski** [comment]
One way is to pass the output path as a user-defined arg (see https://webpack.js.org/guides/environment-variables/ for more details):
```javascript
// webpack.config.js
module.exports = env => {
    Encore.setOutputPath(env.OUTPUT_PATH);
    // other Encore stuff here
    return Encore.getWebpackConfig();
};
```
```bash
> yarn dev --silent --env.OUTPUT_PATH="public/build-dev/"
```
Usually, it's not a good idea to be building or copying any development-related files to the production environment due to it being a more error-prone process as well as introducing potential security vulnerabilities. The flow that I found works best is to build assets in the CI step before deployment and copy only the compiled artifacts, app code, and runtime packages to the production environment during the deployment step. This is easy to set up on GitLab/Bitbucket and probably GitHub as well.

**Comment by fmarchalemisys** [comment]
Thanks for the hint. I'll try to switch to a CI at some point.

I think `env.OUTPUT_PATH` should do the trick but I went for symlinks switching. The build directory is symlinked to `build-dev` or `build-prod` depending on whether encore is called in dev or prod mode. So, encore builds the files in one directory or the other while the already generated files are served through another symlink.
