### ISSUE TITLE
4 minutes compiling

### ISSUE THREAD

**Issue by natoli66** [symfony/webpack-encore#468]
Hello everyone,
This might be just me asking for a little help,
What's happening is that I had to take back a symfony project and I'm not yet mastering it perfectly.

Here is what happens when I try to compile with `docker-compose exec node yarn encore dev`

```console
yarn run v1.9.4
$ /var/www/myproject/node_modules/.bin/encore dev
Running webpack ...

Node#moveTo was deprecated. Use Container#append.
 DONE  Compiled successfully in 196248ms          14:27:30

 I  110 files written to public/build
Done in 209.42s.
```

Here is my webpack.config.js

```javascript
var Encore = require('@symfony/webpack-encore');

Encore
    .enableSassLoader(function(sassOptions) {}, { resolveUrlLoader: false })
    .setOutputPath('public/build/')
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableSourceMaps(!Encore.isProduction())
    .enableVersioning(Encore.isProduction())

    .addEntry('js/app-front', './assets/js/app-front.js')
    .addEntry('js/app-back', './assets/js/app-back.js')
    .addStyleEntry('css/app-front', './assets/css/app-front.scss')
    .addStyleEntry('css/app-back', './assets/css/app-back.scss')

    .enableSassLoader()
    .autoProvidejQuery()
    .autoProvideVariables({ Waves: 'node-waves' })
    .enableVueLoader()
    .enablePostCssLoader()
;

var config = Encore.getWebpackConfig();

config.watchOptions = { poll: true, ignored: /node_modules/ };
module.exports = config;
```

It also takes a really long time loading pages
![Long page loading](https://i.imgur.com/wTMDZ8a.png)

Could someone please give me a way to resolve this, or atleast make me understand it, it is actually really hard to work with that much compilation duration...

Thanks for reading this

**Comment by medymik** [comment]
Cleanin anf enable source & Versioning use it after all

**Comment by natoli66** [comment]
Thanks for the advice, but it didn't speed up my compilation time at all actually...

**Comment by weaverryan** [comment]
4 minutes is WAY slow for a development build, unless your app is absolutely HUGE. My guess is that something is going on with your Docker setup - perhaps a networked filesystem volume is very slow, so all of Webpack's processing is done over a slow, network volume.

I'm sorry I can't offer more help - but I *can* tell you that this is definitely not a "correct" situation - something is not right. But, it's not likely due to your Encore configuration (the advice from @karameloso may speed things up, but it's SO slow that my instinct is that something else is happening).

Cheers!
