### ISSUE TITLE
shared entry (vendor) not included if file is empty

### ISSUE THREAD

**Issue by etshy** [symfony/webpack-encore#489]
I have some js/css files that always needed (css/js framework/library).

Most of my pages doesn't need a specific js file so I made an empty js file `main.js` that contain nothing.

Its purpose is to always import at least one `encore_entry_link_tags` and `encore_entry_script_tags` to always have my `vendor` in all of my pages.

If a page need specific JS, I import another entry, that also contains the `vendor` thanks to sharedEntry and I don't import my empty `main.js`.

The thing is, during compilation, if the entry file is empty it doesn't include the sharedEntry.
It generate something like that
```
"main": {
      "js": [
        "/rapp/build/runtime.a8923592.js",
        "/rapp/build/main.acf976c3.js"
      ]
    }
```

I have to add the following js code to generates the wanted entrypoint, with vendor
```
$(function () {

});
```
and it generates this, like expected
```
"main": {
      "js": [
        "/rapp/build/runtime.a8923592.js",
        "/rapp/build/vendor.e3671ec5.js",
        "/rapp/build/main.acf976c3.js"
      ],
      "css": [
        "/rapp/build/vendor.cc4b0297.css"
      ]
    }
```

I tried using "simpler" code in `main.js` like creating a `const`, just to have a bit of JS in the `main.js` but it seems to not be enough to include the vendor.

My question is, why can't I make my file empty, and have my vendor included in the `main` entrypoint ?

**Comment by weaverryan** [comment]
Hi there!

To be honest, I don’t know :). This logic is handled by the SplitChunksPlugin from Webpack, which is admittedly complex. However, it may make sense: if main.js is empty, then Webpack doesn’t think you need anything in the vendor entry. As soon as you put the $ in that file, thanks to the autoProvidejQuery() function (my guess is you have this enabled), Webpack interprets this as a require statement for jquery. Suddenly your main entry DOES need the contents in that file, and so it’s added.

My advice would be to explicitly require any vendor libs you want to “pre-download” from main.js so Webpack knows what’s important to you. There could be some feature to ask Encore for a list of all the split vendor chunks so that you could literally just include those for download, but that doesn’t currently exist.

Cheers!

**Comment by etshy** [comment]
Ok I guess I'll add my custom css/js that is needed everywhere in my `main.js` and include the `main` entry in all my layout then.

Thanks a lot.
