### ISSUE TITLE
Document include_node_modules option

### ISSUE THREAD

**Issue by mfleonhardt** [symfony/webpack-encore#528]
I just spent two days trying to figure out the right way to include an ES6 module in babel.  Awesome that the feature exists (https://github.com/symfony/webpack-encore/pull/401) but would be great to see that documented here: https://symfony.com/doc/current/frontend/encore/babel.html.

**Comment by Lyrkan** [comment]
Hi @mfleonhardt,

I'm a bit confused... it is documented on that page:

![image](https://user-images.githubusercontent.com/850046/53207163-4592ee80-3633-11e9-8cc1-12d6674e1001.png)

Did you mean that it's not clear enough and should also be explained in its own section?

**Comment by mfleonhardt** [comment]
Sorry--that was a hastily typed description.  I don't think it necessarily requires its own section, but I definitely "read past it" the way it is currently written.  It might just be how the text lays out, but I think it would be better to be more explicit (and in keeping with the rest of Symfony documentation) to separate descriptive comments from functional configuration.  I think even just the syntax highlighting would make a big difference.

Of course, a full configuration reference would be awesome.

`
Encore
    // ...

    .configureBabel(function(babelConfig) {
        // add additional presets
        babelConfig.presets.push('@babel/preset-flow');

        // (Off topic, but...) preset-env is already included, but you can configure it here
        const preset = babelConfig.presets.find(([name]) => name === "@babel/preset-env");
        if (preset !== undefined) {
            preset[1].useBuiltIns = "usage";
        }

        // no plugins are added by default, but you can add some
        babelConfig.plugins.push('styled-jsx/babel');
    }, {
        // node_modules is not processed through Babel by default
        // but you can whitelist specific modules to process
        include_node_modules: ['foundation-sites']

        // or completely control the exclude
        exclude: /bower_components/
    })
;
`

**Comment by Lyrkan** [comment]
I created a PR in symfony-docs to uncomment the existing options (https://github.com/symfony/symfony-docs/pull/11051).

I didn't add the `useBuiltIns` thingy since it may be a bit confusing and it'd probably be better to address the most common use cases by adding new options (see #521 for instance).

As for the full configuration reference we currently redirect people to the JSDoc from the `index.js` file (it should also be available in IDEs' autocompletion):

https://github.com/symfony/webpack-encore/blob/853e0f97a20ee664143152078fd285f0cfd27bc1/index.js#L60-L1235

I kinda agree it's starting to become quite a long read though... maybe there's something we could do to improve that (/cc @weaverryan)

**Comment by javiereguiluz** [comment]
@Lyrkan your pull request in Symfony Docs (https://github.com/symfony/symfony-docs/pull/11051) has been merged. Thanks.
