### ISSUE TITLE
Color issue with "Install ... to use ..." feature

### ISSUE THREAD

**Issue by Kocal** [symfony/webpack-encore#533]
Ref: #520

If we have a light theme, the word `Install` is unreadable:
![selection_301](https://user-images.githubusercontent.com/2103975/53802699-c959ae80-3f42-11e9-943c-bff991fe5000.png)

It works fine with dark theme:
![selection_302](https://user-images.githubusercontent.com/2103975/53806133-77b62180-3f4c-11e9-80f4-fe21313cba12.png)

It would be nice if it take the same color than `Running webpack ...`, `yarn dev-`, `to use`... which is the default color.

I quickly checked the source code on GitHub but I wasn't able to find where the problem apprears.

Thanks!

**Comment by Lyrkan** [comment]
I think that's caused by [`pretty-error`](https://www.npmjs.com/package/pretty-error), the following snippet should give you the same result:

```js
const PrettyError = require('pretty-error');
const chalk = require('chalk');

const pe = new PrettyError();
console.log(pe.render(
  `Install ${chalk.green('webpack-notifier')} to use ${chalk.green('enableBuildNotifications()')}`
));
```

And here is an issue that's probably related: https://github.com/AriaMinaei/pretty-error/issues/7

**Comment by Kocal** [comment]
Yep that's a pretty-error issue! :)
![selection_304](https://user-images.githubusercontent.com/2103975/53817578-100cd000-3f66-11e9-9cc0-fc505b9ccdd8.png)

I found a workaround by using `chalk.reset`:
```diff
const PrettyError = require('pretty-error');
const chalk = require('chalk');

const pe = new PrettyError();
console.log(pe.render(
-  `Install ${chalk.green('webpack-notifier')} to use ${chalk.green('enableBuildNotifications()')}`
+  chalk`{reset Install ${chalk.green('webpack-notifier')} to use ${chalk.green('enableBuildNotifications()')}}`
));
```
![selection_305](https://user-images.githubusercontent.com/2103975/53817679-48aca980-3f66-11e9-8267-248e30465dbe.png)

That's not ideal but it can fix the issue. :thinking:

**Comment by Lyrkan** [comment]
The issue is that we can't really do it in some cases...

That module is called in a global try/catch [here](https://github.com/symfony/webpack-encore/blob/110d9175ec1eb831e90c5006d5517767ee176ab7/index.js#L1295) (also a bit below but that one shouldn't be a problem) and as you can see it takes the exception as a parameter.

Since we don't know what will cause an exception we can't assume that it will always be a string and use `chalk.reset` on it.

Of course we could check `if (typeof error === 'string')` before, but that would only fix it for the few cases where it's a string.
