### ISSUE TITLE
Use APP_ENV when running yarn encore

### ISSUE THREAD

**Issue by Isinlor** [symfony/webpack-encore#537]
Would it be possible to utilize `APP_ENV` variable when running `yarn encore`?

So instead of `yarn encore dev` or `yarn encore production` I would do `yarn encore`. 

More explicit option would be `yarn encore env` that selects dev or production based on `APP_ENV`.

This would avoid duplication of install/deploy configurations between production and development.

Rest of Symfony is doing that already.

Moved from: https://github.com/symfony/symfony/issues/30503

**Comment by Lyrkan** [comment]
Hi @Isinlor,

Is there a reason that you can't do something like `yarn encore "$APP_ENV"`?

I'm not entirely against adding a case where, if the env argument is not set, Encore would try retrieving it from an environment variable but:

* I'm really not sure that's needed
* If we go with it, it probably should be `NODE_ENV` (since that's what most Node.js apps use)

**Comment by Isinlor** [comment]
I think actually `yarn encore "$APP_ENV"` works for me. I didn't notice that `yarn encore prod` is valid.

Thanks for quick help!
