### ISSUE TITLE
Couldn't open png image after processing

### ISSUE THREAD

**Issue by guillaumepacquet** [symfony/webpack-encore#546]
Hello everyone,

I've got some issue with my build, when I build my scss file, the png images are copied in my build folder but I cannot open it, it's corrupted. that's weird because I don't have this issue with my svg. Can you help me ?

Here my sources:

main.scss
```
.stf-search-bg {
    background: url(../images/bg-empty-state.svg) 50% -20px no-repeat;
    padding-top: 400px;
    margin-top: 15px;

    @include e('icon') {
        background: url(../images/icon-search.png) 0 0 no-repeat;
        background-size: 140px auto;
        color: #888;
        display: block;
        height: 140px;
        left: 0;
        margin-left: auto;
        margin-right: auto;
        position: absolute;
        right: 0;
        text-align: center;
        top: -230px;
        width: 140px;
    }
}
```

webpack.config.js
```
let Encore = require('@symfony/webpack-encore');

Encore
    .setOutputPath('web/build/')
    .setPublicPath('/build')
    .cleanupOutputBeforeBuild()
    .enableVersioning(Encore.isProduction())
    .addEntry('js/app', './assets/js/index.js')
    .addStyleEntry('css/style', ['./assets/less/main.less', './assets/sass/main.scss'])
    .enableLessLoader()
    .enableSassLoader()
    .enableVueLoader()
    .addLoader({
        loader: 'eslint-loader',
        options: {
            fix: !Encore.isProduction(),
            ignorePattern: ['*.less', '*.scss', '*.svg', '*.png']
        }
    })
    .enableVueLoader()
;

module.exports = Encore.getWebpackConfig();
```

package.json
```
{
  "devDependencies": {
    "@babel/core": "^7.4.0",
    "@babel/preset-env": "^7.4.2",
    "@symfony/webpack-encore": "^0.24.0",
    "less": "^3.8.1",
    "less-loader": "^4.1.0",
    "node-sass": "^4.11.0",
    "sass-loader": "^7.1.0",
    "vue": "^2.5.17",
    "vue-loader": "^15.3.0",
    "vue-template-compiler": "^2.5.17"
  },
  "dependencies": {
    "@babel/polyfill": "^7.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "bootstrap-vue": "^2.0.0-rc.11",
    "encore": "^0.0.30-beta",
    "eslint": "^5.4.0",
    "eslint-loader": "^2.1.0",
    "eslint-plugin-vue": "^4.7.1",
    "vue-clipboard2": "^0.2.1",
    "vue-notification": "^1.3.13",
    "vue-resource": "^1.5.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1",
    "vuex-persistedstate": "^2.5.4"
  }
}
```

Thank you.

**Comment by weaverryan** [comment]
Hey! 

Interesting. I can’t think of any reason your pngs would be touched at all, other than a simple copy. Have you tried looking in the file - was it... for example turned into a text file, or still an image but truncated?

**Comment by Lyrkan** [comment]
Hi @guillaumepacquet,

Could you try temporarily removing the ESLint loader?

Right now it applies on all files, including images: the `ignorePattern` option only excludes them from being checked but they still go through the loader. I'm guessing that somehow the whole process doesn't like binary files and ends-up corrupting them.

If you want to add that loader manually you'll have to add a `test` rule that only includes JS files (see https://github.com/webpack-contrib/eslint-loader#usage), but I would recommend you to simply use [`Encore.enableEslintLoader()`](https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/index.js#L946-L978) instead.


Also, not really related, but you don't need to add some of the dependencies listed in your `package.json` (`@babel/core` and `@babel/preset-env`)  since they are [already handled by Encore](https://github.com/symfony/webpack-encore/blob/0facc4d0442003809a438e2537f5adffffb48d78/package.json#L27-L58). Most of the time it won't be a big deal but it can end-up causing annoying issues since you could install different versions from the ones that are expected by Encore.

**Comment by guillaumepacquet** [comment]
Hi @Lyrkan,

You're right, when I remove ESLint loader it's working. I will use `Encore.enableEslintLoader()` and thx for the advise on my package.json.
