### ISSUE TITLE
How to point webPack encore to public folder without using symfony server

### ISSUE THREAD

**Issue by hous04** [symfony/webpack-encore#580]
I'm using Symfony 4 and this is the first time I use webPack encore.

when I access my website through the url http://127.0.0.1:8000/ the css is loaded.

But using this url http://localhost/website/public/index.php/ ` {{ encore_entry_link_tags('app') }}` doesn't point to **public/build**, and the css is no more loaded.
   
    // this is wrong path, css file is not loaded
    <link rel="stylesheet" href="/build/app.css">

**Should be like this to work**

    <link rel="stylesheet" href="/website/public/build/app.css">

In local , I can solve the problem by using the first url but not in production on the public server.

**Comment by weaverryan** [comment]
Hi there!

Welcome to Encore :). If your app lives in a subdirectory (not at the root of your domain), you need to tell Encore about this: https://symfony.com/doc/current/frontend/encore/faq.html#my-app-lives-under-a-subdirectory

If your subdirectory is different locally versus on prod, you could set an environment variable when running the encore command then read that in Webpack.config.js to toggle the setting.

But, why are you deploying to a subdirectory on production? Is that just a requirement of your project or server?

Cheers!

**Comment by ziscode** [comment]
In "localhost" server i just remove "/" from .setPublicPath('build') and work.

**Comment by php4fan** [comment]
> If your app lives in a subdirectory (not at the root of your domain), you need to tell Encore about this

That seems like a design flaw in Encore to me. I **shouldn't need to tell it about** the path prefix any more than I need to tell it about the domain name. (note that outside of Webpack one usually doesn't need to tell Symfony about that: links and routes etc all work out of the box whether the application lives under a directory or not, as one would expect).
Even worse if that needs to be known **at compile time**. Because then it means that I cannot move the application from a folder to another, or change the root folder name in Apache's configuration, without rebuilding the assets (note I wouldn't need to do that if moving from a domain to another).

> If your subdirectory is different locally versus on prod, you could set an environment variable when running the encore command then read that in Webpack.config.js to toggle the setting.

Can we have a full **example of that in the documentation**? This is a pretty common use case.

> But, why are you deploying to a subdirectory on production?

**Why not?** That question reveals the flawed mindset (no offense) behind the flawed design (or behind the choice to not consider the feature important, if you prefer). 
Surely we can agree that I may want to have many applications without having to register many domains, right? So the question is why I would deploy to "mydomain.com/myapp" rather than "myapp.mydomain.com". Well, what about I like it more? The choice of what url to deploy my application under shouldn't be constrained by technical reasons.

I would expect `.setPublicPath('/build')` to automatically point to `/whatever/the/app/root/path/is/build`, or, as the next best thing, to be able to set `.setPublicPath(someSymfonyMagic()+'/build')` or something like that. If not right out of the box, it should be really, really easy (but then, why not just out of the box).
