### ISSUE TITLE
process.env.NODE_ENV is always "development" ?

### ISSUE THREAD

**Issue by jfcherng** [symfony/webpack-encore#610]
My minimal problematic repo: https://github.com/jfcherng/symconty-encore-NODE_ENV-question

I would like to config PostCSS with `postcss.config.js` basing on the current env. So I write codes like https://git.io/fjPut, but I find it not working since `ctx.env` is always `undefined` somehow and `process.env.NODE_ENV` is always `development`.

When I run `$ yarn encore production` or `$ yarn build`, [it shows](https://git.io/fjPuq)
```
ctx.env : undefined
process.env.NODE_ENV : development
```

Do I miss something? What's the suggested way to make `postcss.config.js` (or other plugins' configuration js files) env-sensitive?

---

The current solution that I figure out is [adding](https://git.io/fjPum)
```js
process.env.NODE_ENV = Encore.isProduction() ? 'production' : 'development';
``` 
right after 
```js
const Encore = require('@symfony/webpack-encore');
```

After doing so, I get

```
ctx.env : production
process.env.NODE_ENV : production
```

**Comment by Lyrkan** [comment]
Hi @jfcherng,

We don't set any env var from Encore, so `NODE_ENV` is supposed to be `null` in that case... but what happens is that the `postcss-load-config` sets it to `development` when it is falsy: https://github.com/michael-ciniawsky/postcss-load-config/blob/bdaf431ef1142b5d0253aeb534aad8f42e46877e/src/index.js#L47-L60

I'm not sure why they do that instead of setting `ctx.env` which stays undefined in this case... (ping @michael-ciniawsky).

Anyway, you can either:
* define that var yourself, either as you already do in the `webpack.config.js` file or by passing it to the CLI: `NODE_ENV=production yarn encore prod`
* use `ctx.webpack.mode`

**Comment by jfcherng** [comment]
@Lyrkan Thanks for your suggestion.

Since Encore is not setting `NODE_ENV`, is there a down side doing the following statement?

```js
process.env.NODE_ENV = process.env.NODE_ENV || Encore.isProduction() ? 'production' : 'development';
```

**Comment by jfcherng** [comment]
`ctx.webpack.mode` looks always available as well. Thanks!

**Comment by Lyrkan** [comment]
> Since Encore is not setting NODE_ENV, is there a down side doing the following statement?

Probably not, the value just won't be available to things executed before the Webpack config file is read... which shouldn't be a big issue.
