### ISSUE TITLE
[BUILD] Warning about core-js

### ISSUE THREAD

**Issue by Guikingone** [symfony/webpack-encore#617]
Hi everyone 👋 

Small question about `core-js`, when I try to build my project assets, here’s the warning that I get: 

```bash
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3
```

My current dependencies does not require it but it seems that Encore need it (as it’s defined in the dev-dependencies), is there any way to get rid of this warning ? 🤔 

I’ve tried to install it as a project dependencies (using `yarn add core-js@2` || `yarn add core-js@3`) but the warning continue to appear. 

Thanks for the feedback and have a great day 🙂

**Comment by Lyrkan** [comment]
Hey @Guikingone,

Yes you can get rid of it (and probably should!)

When using Babel polyfills with `useBuiltIns: 'entry'` or `useBuiltIns: 'usage'` you also need to add `core-js` to your dependencies **and** tell Babel which version you chose (since it doesn't work the same way with `core-js@2` and `core-js@3`).

As the warning says, for now it assumes that you are using `core-js@2` but it's likely to change later on, so you can use the `corejs` option that was added to `Encore.configureBabel()` in [Encore v0.26.0](https://github.com/symfony/webpack-encore/releases/tag/v0.26.0):

```js
Encore.configureBabel(() => {}, {
    useBuiltIns: 'entry',
    corejs: 3
})
```

Also if you are using `entry` and not `usage`, don't forget to import `core-js` once (and only once) in your entrypoints.

**Comment by Guikingone** [comment]
Hey @Lyrkan 

Thanks for the fast feedback, it help me to get rid of the warning, I’ve seen that it was explained in the changelogs on https://yarnpkg.com/fr/ (maybe should I’ve start in the changelogs the next time 😄 )

Thanks again for the help and have a great day 🙂
