### ISSUE TITLE
Shared entry fails with configureFilenames

### ISSUE THREAD

**Issue by XWB** [symfony/webpack-encore#618]
In extend to https://github.com/symfony/webpack-encore/issues/615

Imagine the following configuration:

```js
Encore
    .createSharedEntry('js/functions, './assets/js/functions.js')
    .addEntry('js/js1', './assets/js/js1.js')
    .addEntry('js/js2', './assets/js/js2.js')
    .enableVersioning(Encore.isProduction())
    .configureFilenames({
        js: '[name].js?[contenthash:8]',
        css: '[name].css?[contenthash:8]'
    });
;
```

Now when I run `yarn encore dev`, the command fails with the following error:

```
Error: Invalid number of files for chunk js/functions - got
    at getChunkFilename (node_modules/@symfony/webpack-encore/lib/webpack/shared-entry-concat-plugin.js:33:15)
    at ....

Error Command failed with exit code 1.
```

When I remove `configureFilenames`, everything works as expected. Any idea how I should resolve this?

Note: I use dynamic imports.

**Comment by Lyrkan** [comment]
Hi @XWB,

Thanks for the report I can reproduce the issue on my end (without dynamic imports).

I suspect that the following check wrongly removes a file from `jsFiles` because it ends by `.js?xxxxx` instead of `.js`:

https://github.com/symfony/webpack-encore/blob/9a3cb43e880f10c54e8319b76433058137da78d2/lib/webpack/shared-entry-concat-plugin.js#L28-L30
