### ISSUE TITLE
Add a way to know if Encore is running in dev-server env or not, in Twig

### ISSUE THREAD

**Issue by Kocal** [symfony/webpack-encore#623]
Hi, it's a following of symfony/webpack-encore-bundle/issues/75.

For the Encore part, maybe it can create a new `.json` file (e.g.: `encore.json`) which will contains something like this:
```json
{
  "env": "dev-server" 
}
```

or
```json
{
  "prod": false,
  "dev": false,
  "dev-server": true
}
```

I'm in favor of the second solution, since we can only have three Encore different envs.

**Comment by pscheit** [comment]
hi! Why do you need this information in twig?

**Comment by Kocal** [comment]
See symfony/webpack-encore-bundle/issues/75 :P

**Comment by Lyrkan** [comment]
Hey @Kocal,

I'm wondering if that's really the info you are looking for there... in your use case it doesn't fail because you are using the dev server, but because you have full URLs instead of paths.

For instance, having something like `Encore.setPublicPath(Encore.isDev() ? '/build' : 'https://<cdn>/')` would result in the same issue.

Of course we could also add `encore_is_dev()` and `encore_is_prod()` but I have some doubts about how useful it would actually be.

**Comment by Kocal** [comment]
Hum, you're right.

Mmmh.. Yes, configuring Encore to use a CDN + using `encore_is_dev_server()` won't solve any issue.

I think I will go for the first solution I got, iterate on Encore `email`/`email-responseive` entries, check if it starts with `https://` and yes so I won't inline my CSS.

I'm closing for now. Thanks @Lyrkan :)
