### ISSUE TITLE
We can not choose a proper build for Vue.js

### ISSUE THREAD

**Issue by esynaps** [symfony/webpack-encore#625]
I would like to use the Vue.js build like defined by my alias : 

```
{
      'vue$': Encore.isProduction() ? 'vue/dist/vue.runtime.min.esm': 'vue/dist/vue.runtime.esm',
}
```
but it is not possible because of this file which rewrites my alias in an unwanted way. 

https://github.com/symfony/webpack-encore/blob/5640271a87e63048b8ae261d210922b4972cab69/lib/config-generator.js#L103

Why this build precisely? Why is it not configurable? The solution I found to work around the problem:

```
let config = Encore.getWebpackConfig()
config.resolve.alias = {
      'vue$': 'vue/dist/vue.runtime.esm',
    }
module.exports = config
```

I'm using the 0.28.0 version of "@symfony/webpack-encore"

**Comment by Lyrkan** [comment]
Hello @esynaps,

You're right that it should be possible to overwrite pre-defined aliases using `Encore.configureAliases(...)`, we should probably only assign `this.webpackConfig.aliases` after all the presets have already been applied:

https://github.com/symfony/webpack-encore/blob/5640271a87e63048b8ae261d210922b4972cab69/lib/config-generator.js#L99

That being said I'm not certain that it's needed in your case... from [Vue.js documentation](https://vuejs.org/v2/guide/installation.html#Development-vs-Production-Mode):

> CommonJS and ES Module builds are intended for bundlers, therefore we don’t provide minified versions for them. You will be responsible for minifying the final bundle yourself.

**Comment by esynaps** [comment]
From what I understood from the documentation (I could be wrong), I do not need to compile it. That's why I want to use vue.runtime.esm instead of vue.esm.js

Then, the solution that you propose (to apply the aliases at the end) seems to me to be viable.

**Comment by Lyrkan** [comment]
> From what I understood from the documentation (I could be wrong), I don't need the compiler. That's why I want to use vue.runtime.esm instead of vue.esm.js

Changing the alias to a minified version won't exclude the file from the compilation process. Webpack will just process the already minified file, include the parts you use into your build and re-minify everything again.

And as noted in the quote from my previous comment, there is no `vue/dist/vue.runtime.min.esm.js` file (you can check it yourself by looking at the content of the `node_modules/vue/dist` folder), because the `vue.runtime.esm.js` is intended to be used with something like Webpack.

**Comment by esynaps** [comment]
I realized before your answer and I replaced my alias `Encore.isProduction() ? 'vue/dist/vue.runtime.min.esm': 'vue/dist/vue.runtime.esm` with `vue/dist/vue.runtime.esm`

On the other hand, as I indicated in my previous post, there is still an interest to use `vue/dist/vue.runtime.esm` rather than `vue.esm.js` (forced by webpack again)

**Comment by Lyrkan** [comment]
Oh sorry, I misread your comments... I thought we were already aliasing it to `vue.runtime.esm` and the issue was with the minified/not-minified selection.

I agree with changing it so pre-defined aliases can be overwriten (if someone wants to open a PR, that should be an easy fix), in the meantime doing it the following way is probably the way to go:

```js
const config = Encore.getWebpackConfig();

// No need to replace the whole `config.resolve.alias` object
config.resolve.alias['vue$'] = 'vue/dist/vue.runtime.esm';

module.exports = config;
```
