### ISSUE TITLE
How to properly use this plugin with dynamic files?

### ISSUE THREAD

**Issue by yellow1912** [symfony/webpack-encore#628]
Hello,

Sorry if my question's title was not clear enough. Please let me explain:

In my symfony project, I have a system of "widgets" that can be dynamically dropped in any page to build the layout and content. Each widget will require its own css/js files and libraries which I do have a built-in php class to handle the versioning etc. 

In any case, the system is capable of generating a list of assets required for each pages. Reading the document for Encore, I understand that I will need a webpack.config.js file, which contains all the entries (lets say 1 entry per web page).

I also want to obtain the final results to transfer to my file server (aws s3)

So it seems like I have to:
1. Pre-combine all the assets into 1 single file since each entry accept only 1 file?
2. Dynamically build the webpack.config.js file with php code
3. Run the encore node command via php (calling shell perhaps? I wonder how to know when the compiling is done via shell)
4. Get the compiled file and the upload that to the file server

Please let me know if this seems right or should I give up on the idea of using Encore. I really like all the nice things that Encore has to offer.

**Comment by stof** [comment]
when you say "dynamically", do you mean that such changes happen without any deployment of the project ?

If yes (and so new combination being added at any time), I would go for building one entry importing all your widgets (and making sure that your widgets support being imported on a page not needing them without having bad effects). This is the simpler solution.
If you have lots of code, you could split that entry into multiple ones (based on widgets that are likely to used together) and then keep a map of which entry contains the code of each widget to know which one you need to load.
I would not go the way of running encore at runtime on your server to generate dynamic page-specific bundles, as that would be too long to run while the browsers waits for it (and we need it to be done by the time the browsers wants the asset, so asynchronous work is not really an option).

If your combination of widgets only change during deployment (because this "dynamically dropped" is done in the source code), I see several options:
    - same than above (simple way, fine if you don't have too many widgets)
    - identify all combinations of widgets you need, and define an entrypoint for each of them (this may involve scripting the generation of entrypoint and of a file listing them that can be used by the webpack.config.js to keep things simpler), and then import the right entry on each page
    - identify the combinations of widgets, and then group them into a few buckets, have an entrypoint for each of this bucket and choose the right entrypoint for each page. This is essentially a middle ground between previous one (first one being "1 bucket for all" and second one being "1 bucket each). This works pretty well if you can make this grouping smart to benefit from browser cache . For reference, at Incenteev, I use this strategy: we have 2 buckets, one for admin-only configuration pages and one for user-facing pages (some widgets are in both buckets), which avoids loading config-only widgets for non-admin users and benefit from the HTTP cache for everyone.

**Comment by yellow1912** [comment]
@stof Thank you very much for the very detailed explanation.

The widgets are built (dragged and dropped) dynamically on live site, but we can afford the build time by pushing the page into build mode and run a worker to update the assets. The file is only published/re-published once the build is done.

It's difficult to know which widgets are used together, we have hundreds of them which can be mixed to create different layouts (and the number keeps growing). From what you described, I think I can do this (if I understand it right):

1. Get the list of all the widgets assets for a single file
2. Build an entry file that import all the assets
3. Include the entry in webpack.config.js file

All the 3 above can be done via php I think (which makes it much easier for me)

Then after that, all I have to do is:
1. Use php shell exec to run the encore build command
2. Loop through all the generated files and pushed to the server.
3. Inject the assets links back to the HTML at the right locations.

Does it look okie or what do you think?

**Comment by Lyrkan** [comment]
Hi @yellow1912,

What about using JS dynamic imports?

Something along the lines of (without any safety check/error handling):

```js
// Select all `<widget>` tags, but you could also use
// something else like a class... or add something in
// your page that lists all the widgets that should be
// loaded.
document.querySelectorAll('widget').forEach((element) => {
  const widgetType = element.dataset['widgetType'];
  import(`./widgets/${widgetType}`)
    .then(module => {
      // Call something from `module` using `element`
      // to initialize the widget on it.
    });
});
```

Then you would only need to include the resulting entry from that file on all the pages that can contain a widget and use the right tags to initialize them, for instance:

```html
<widget data-widget-type="foo" />
<widget data-widget-type="bar" />
<widget data-widget-type="baz" />
```

This would only load `./widgets/foo`, `./widgets/bar` and `./widgets/baz`, even if you have hundreds of other widgets available.

**Comment by yellow1912** [comment]
@Lyrkan Interesting idea. The only concern is the loading speed. Lets say on average 1 page contains 10-20 widgets, in the worst case scenario we may have 10-20 asset files. I think requiring them on the fly like that may be too slow? 

The idea is interesting though, perhaps for using with some types of script that can be loaded on demand.

**Comment by stof** [comment]
you could add `<link rel="preload">` for each of the widgets used by the page to help improving performance.

Note however that this dynamic import solution might not play well with webpack, as webpack will try to resolve these at build time and may decide to bundle them all together rather than bundling them separately. This needs to be tested to see which way it uses.

And to be able to preload things easily, you may need something like https://github.com/symfony/webpack-encore/issues/573 (and a way to figure out how to name such dynamic imports)

**Comment by Lyrkan** [comment]
> The only concern is the loading speed. Lets say on average 1 page contains 10-20 widgets, in the worst case scenario we may have 10-20 asset files. I think requiring them on the fly like that may be too slow?

I'm not sure it'd be that big of a deal since you'll end-up loading almost the same amount of data, but split up between multiple files. Unless you have hundreds of async modules it shouldn't add a big overhead.

That would probably even be better than loading all of the widget synchronously in a big single file since it won't block the rest of the page.

> Note however that this dynamic import solution might not play well with webpack, as webpack will try to resolve these at build time and may decide to bundle them all together rather than bundling them separately. This needs to be tested to see which way it uses.

In this case it should create separate files.
It's the same kind of trick that you can use with, for instance, Moment.js to avoid loading all the locales by default (after ignoring the translation files from the build).

**Comment by Lyrkan** [comment]
Also, if you want to make sure it creates a different file for each module and avoid filenames like `0.js`, `1.js`, `2.js`, etc., you can always explicitely set `webpackChunkName`:

```js
import(/* webpackChunkName: "widget-[request]" */ `./widgets/${widgetType}`)
```

**Comment by yellow1912** [comment]
@Lyrkan perfect, thank you very much. All noted.
