### ISSUE TITLE
copyFiles does not support pattern match placeholder

### ISSUE THREAD

**Issue by dontub** [symfony/webpack-encore#647]
In https://github.com/webpack-contrib/file-loader#placeholders there's the pattern match placeholder `[N]` documented:
> The n-th match obtained from matching the current file name against the `regExp`.

I would expect that `copyFiles` would use the matches from `pattern`, though `[N]` is not replaced. For example in the following code
```
Encore.copyFiles({
     from: './assets/',
     to: '[path][0]',
     pattern: /.*/,
});
```
`[0]` should be replaced by the entire tested string, though the resulting filename is always `[0]`.

**Comment by stof** [comment]
This is the doc for file-loader specifically. copyFiles is not abotu configuring the file-loader (as these files are precisely not loaded from your JS or CSS files, which is why they need explicit copying).

**Comment by dontub** [comment]
https://github.com/symfony/webpack-encore/blob/89929bb17ea4e20783eab7b24b3e881149bf75e1/index.js#L531 links to the file-loader documentation saying
> You can add all the placeholders supported by the file-loader.

**Comment by Lyrkan** [comment]
We are indeed [using the `file-loader` internally](https://github.com/symfony/webpack-encore/blob/master/lib/webpack/copy-files-loader.js) for that feature.

From what I understand that specific placeholder does not work because it requires the `file-loader` to be initialize with a `regExp` option, which is currently not the case (we only use the `pattern` option internally, it is not passed to the loader).

I think it wasn't available yet when I worked on `copyFiles`, but unless I'm missing something it could probably be added relatively easily.
