### ISSUE TITLE
HMR, port with hostname, 404s in Symfony - any possible solutions?

### ISSUE THREAD

**Issue by versedi** [symfony/webpack-encore#681]
Related: https://github.com/symfony/symfony/issues/7592

When I use encore with HMR and access the page with port number, eg. http://app.local:9001/route/someid/ some routes are parsed badly and the page isn't found. When the port number is removed so url looks like this: http://app.local/route/someid/ the router parses it correctly.

Unfortunately this renders hot reloading half useless cause you can't actually navigate through the website but have to enter manually the page you want to visit without port.

Do you guys have any ideas how we could solve this?

**Comment by Lyrkan** [comment]
Hi @versedi,

I'm having a hard time understanding your setup... could you maybe share your conf and the commands you run?

Also, what do you mean by "some routes are parsed badly"?

**Comment by versedi** [comment]
We're using `Limenius/ReactBundle` and it's Symfony responsibility for calling proper controller methods depending on the path that was accessed to create an initialState for Redux so the client doesn't have to fetch necessary data anymore on the first page open.

Let's say we have a typical CRUD on that, and there's a view like:

```
path: /message/{id}
```

When you visit this path via: `yourapp.local/message/123` the controller method gets called and everything works properly.

When I run:
`encore dev-server --port 9001 --hot --host=yourapp.local --watch --mode=development`

 and access `yourapp.local:9001/message/123` the controller method doesn't get called and Symfony throws a 404 Page not found. 

This is affecting both projects Laravel and Symfony since they are using the same routing classes. 

It doesn't happen for all routes. The only related thing that I've found was the issue in Symfony I've linked at the top of the issue. 

If I understood correctly In the issue I linked Fabien suggested to create actual route prefix with that port number. Do you think duplicating every route twice on a prefix is viable way to do this? 


Encore devServer config is following if it matters:

```
config.devServer = {
    host: 'yourapp.local',
    port: 9001,
    hot: true,
    index: 'web/app_dev.php',
    liveReload: true,
    historyApiFallback: true,
    disableHostCheck: true,
    public: 'yourapp.local',
    allowedHosts: ['yourapp.local'],
    contentBase: path.join(__dirname, 'web'),
    watchContentBase: true,
    proxy: {
        '*': {
            target: 'http://yourapp.local:80',
            pathRewrite: {
                '/[0-9]+': '',
            },
        },
    },
};
```

**Comment by Lyrkan** [comment]
I see... I usually recommend running the dev-server alongside the server hosting your PHP app (this is, imo, easier to setup and should work quite well with the Webpack Encore Bundle), so I'm not sure how the dev-server's proxy is supposed to work there.

Is the `pathRewrite` intentional ? `http://yourapp.local:80/message` would be called instead of `http://yourapp.local:80/message/123` which could explain the 404.

Maybe you could also try setting the `changeOrigin` option of your proxy rule to `true` (see https://webpack.js.org/configuration/dev-server/#devserverproxy) so the `Host` is set to `yourapp.local:80`, but I'm guessing it would also generate URLs with `yourapp.local:80` instead of `yourapp.local:9001`.

**Comment by versedi** [comment]
It was actually the `pathRewrite` causing it, not sure why I entered it in the first place but it does work properly without it.
