### ISSUE TITLE
Webpack encore requires "babel-eslint" even if not used

### ISSUE THREAD

**Issue by david-wilson-mcn** [symfony/webpack-encore#685]
What i'm trying to use is encore, typescript, react, and linting typescript with using the '@typescript-eslint/parser' parser (since tslint is being deprecated). I got it all working, but my question is why do I still need the 'babel-eslint' package if i'm not using the babel eslint parser? Encore complains that I need it if I enable 'enableEslintLoader'. Here is the relevant parts of my webpack.config.js:
```
    .enableTypeScriptLoader()
    .enableForkedTypeScriptTypesChecking()
    .enableEslintLoader(options => {
        options.parser = '@typescript-eslint/parser'
    })
    .configureLoaderRule('eslint', loader => {
        loader.test = /\.(jsx?|tsx?)$/
    })
    .enableReactPreset()
```
Here is the relevant parts of my .eslintrc.js file:
```
    parser: "@typescript-eslint/parser",
    plugins: [
        "@typescript-eslint",
        "react"
    ],
    extends: [
        "eslint:recommended",
        "plugin:@typescript-eslint/eslint-recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:react/recommended"
    ],
    parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
        ecmaFeatures: {
            jsx: true
        }
    }
```
If I don't have the package and run 'yarn dev-server' I get:
```
Running webpack-dev-server ...

  WARNING   Be careful when using Encore.configureLoaderRule(), this is a low-level method that can potentially break Encore and Webpack when not used carefully.
  Error: Install eslint-loader & babel-eslint to use enableEslintLoader()
    yarn add eslint-loader@^2.1.2 babel-eslint@^10.0.1 --dev

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by Kocal** [comment]
Hi,

This is because Encore already configure ESLint a bit by setting [`parser` to `babel-eslint`](https://github.com/symfony/webpack-encore/blob/master/lib/loaders/eslint.js#L26) and so [`babel-eslint`](https://github.com/symfony/webpack-encore/blob/master/lib/features.js#L106) is required when using `enableEslintLoader`.

We already had an issue with because of this `babel-eslint` already configured (#574) and I've opened a RFC (#657) to make Encore stop configuring ESLint and let the end-user have a full control on ESLint configuration.

For now you have to keep package `babel-eslint` installed even if you don't use it. :confused:

**Comment by Kocal** [comment]
Hi, #687 has been merged.
It means that you will be able to remove `babel-eslint` at the next Encore release! :)

**Comment by weaverryan** [comment]
Awesome :). Closing!
