### ISSUE TITLE
Importing from folder

### ISSUE THREAD

**Issue by pajasry** [symfony/webpack-encore#722]
Hi, I am new in world of webpack-encore. I used to define aliases for root and then importing ` import {history, Role} from '@/_helpers'`.
 I set alias with `let config = Encore.getWebpackConfig();
config.resolve.alias["@"] = path.resolve(__dirname, 'assets/js');
module.exports = config;`
but it still shows **dependencies not found**. What i am missing?

**Comment by weaverryan** [comment]
Hi there!

Welcome to Encore :). I’m not sure what the problem is - but generally-speaking, what you’re doing is fundamentally correct (so it may be some small typo).

However, there is also an easier way - the Encore object has an addAliases() method that allows you to do this more directly. Ultimately, that method does the same basic thing that you’re doing, but using that method (which is easier anyways) might fix whatever small issue it contains.

Cheers!
