### ISSUE TITLE
File-loader not works with different images with same name

### ISSUE THREAD

**Issue by shude** [symfony/webpack-encore#73]
Hi.
I've 2 different images with same name:
```
assets/images/some.png
assets/another_images/some.png
```
In scss file i use both. File-loader copy only first image and skips second.
I have to rewrite the rule in config-generator.js to:
```
{
                test: /\.(png|jpg|jpeg|gif|ico|svg)$/,
                loader: 'file-loader',
                options: {
                    name: `images/[name]_[md5:hash:hex:3]${this.webpackConfig.useVersioning ? '.[hash]' : ''}.[ext]`,
                    publicPath: this.webpackConfig.getRealPublicPath()
                }
            }
```

But is this a right way ?
Second question: how can i overwrite that rule in webpack.config.js ?

**Comment by weaverryan** [comment]
Hey @shude!

Hmm, yes, this makes sense. Without hacking in *any* changes, does simply enabling Encore versioning fix this (`Encore.enableVersioning()`)? That should give each filename a unique hash.

Let me know! But, even if it *does* fix it... we might still want to make a change. And to answer your question, there's currently no way to override that rule in `webpack.config.js`. I expect people may want to do that at some point, but this is the first time anyone has reported wanting that extension point.

**Comment by shude** [comment]
Thank you, @weaverryan!
Indeed, enable versioning fix the problem. But i think it might be more flexible.
Now, we have a hardcoded path for images and fonts and it is not a good solution.

**Comment by Lyrkan** [comment]
Wouldn't it be enough to allow people to use the [`[path]`](https://github.com/webpack-contrib/file-loader/blob/master/README.md#filename-template-placeholders) placeholder (eg. with a `keepAssetsPaths()` method) ?

@weaverryan  You said on Slack that it could be an issue if, let's say, two scss files referenced the same image from a different folder. That shouldn't be the case since the final path is relative to a context that is the same for all the files handled by the loader.

**Comment by Lyrkan** [comment]
Nevermind my previous comment, I thought about it a bit more and it'd probably be better to make it possible to override/disable the predefined image and font loaders entirely.
