### ISSUE TITLE
Fonts and images not working after update

### ISSUE THREAD

**Issue by eberhapa** [symfony/webpack-encore#771]
Hi,

After updating to 0.30.0 fonts and images are not working with npm run watch (build folder empty). With npm run build everything is fine. Did something changed here?

Thanks,
Patrick

**Comment by mfu-aroche** [comment]
Hi! We are running in the same issue at my company, but in our case it's only affecting fonts. I found that the problem comes from pull-request #760 (d697be87). It was working fine (fonts are emitted to build folder) up to revision 2eaa4ad2 and is broken (no font in build folder) since merge at revision 5429553a.

I managed to find it by trying all of them from tag `v0.29.1` (134f47a3) to `v0.30.0` (e597463e), as the bug occurs since `v0.30.0` according to our tests. To install package at specific revision, I used `npm i @symfony/webpack-encore#revhash`.

According to #760, the purpose was to upgrade `clean-webpack-plugin` from `^0.1.19` to `^3.0.0`. Maybe one of its dependencies is the problem...

**Comment by Kocal** [comment]
Can you check if https://github.com/johnagan/clean-webpack-plugin/issues/152 is working for you?

**Comment by Hexa-IT** [comment]
I got the same issue after running: `npm audit fix` wich upgraded it to `v0.30.1`. Fonts can't be loaded when I run `encore dev --watch` or `npm run watch`. But when I run `encore production --watch` or `encore dev` without the watch it works fine.

**Comment by weaverryan** [comment]
Hi!

Try the new `0.30.2` release - in #772, I disabled an option in CleanWebpackPlugin. I believe there is a bug in their "watch" mode - I experienced a similar issue where files (in watch only) would disappear.

If you still have an issue with 0.30.2, please let us know by creating a new issue :).

Cheers!
