### ISSUE TITLE
Support babel option includeNodeModules with pnpm

### ISSUE THREAD

**Issue by leonexcc** [symfony/webpack-encore#785]
The option includeNodeModules of bable doesn't work with [pnpm](https://pnpm.js.org/), since filePath will contain the real path after resolving the link (for example .../node_modules/.pnpm/plyr@3.6.2/node_modules/plyr/...)

After replacing
```
const whitelistedModules = options[optionKey].map(
     module => path.join('node_modules', module) + path.sep
);
```

with 

```
const whitelistedModules = options[optionKey].map(
    module => path.dirname(require.resolve(module + '/package.json'))
);
```

it works as expected.

Also the mapping is currently executed for each file again. This could probably done once outside of the callback.

**Comment by stof** [comment]
Doing `require.resolve` when processing the config will have several issues:

- it restricts that to packages that can be resolved from the root, while the current approach works for any transitive deps too
- it won't work for packages using the new `exports` config (available in Node 13+), as `package.json` might not be an allowed export of the package

also, I don't think the path `.../node_modules/.pnpm/plyr@3.6.2/node_modules/plyr/...` is an issue. This path has `node_modules/plyr/` in it.

**Comment by leonexcc** [comment]
You are right. My issue was that my modules in includeNodeModules were not transpiled and i thought this was the reason. But i used a .babelrc instead of a babel.config.json and the .babelrc is ignored for node modules. Maybe this could be documented somewhere next to the includeNodeModules option.

**Comment by stof** [comment]
Documenting that makes sense.
Or maybe even detecting this case automatically in Encore. Is this possible @weaverryan @Lyrkan ?

**Comment by Lyrkan** [comment]
> Or maybe even detecting this case automatically in Encore. Is this possible @weaverryan @Lyrkan ?

I think we could... we currently check for both files (and `package.json` config) here:

https://github.com/symfony/webpack-encore/blob/a7d76ee0661ddeac35e241e1f48962dbf6123906/lib/config/parse-runtime.js#L88-L104

But before #738 we only had a check for the existence of `.babelrc` files using:

```js
runtimeConfig.babelRcFileExists = (typeof partialConfig.babelrc === 'string');
```

Maybe we could have both of them instead (that will require to refactor some other files to use `babelConfigExists` instead of `babelRcFileExists`):

```js
runtimeConfig.babelConfigExists = partialConfig.hasFilesystemConfig();
runtimeConfig.babelRcFileExists = partialConfig.babelrc !== undefined; // Slightly changed the old check to match https://github.com/babel/babel/blob/af669297efd775016725ee39318cdb391cf00a21/packages/babel-core/src/config/partial.js#L199
```

And then trigger a warning if `configureBabel()` is called with the `includeNodeModules` option when there is a `.babelrc` file (`runtimeConfig.babelRcFileExists`) without any global config (`!runtimeConfig.babelConfigExists`) ?
