### ISSUE TITLE
Usage in combination with babel & jest

### ISSUE THREAD

**Issue by BackEndTea** [symfony/webpack-encore#809]
I'm trying to move a project to webpack encore.

Previously we had a `babel.config.json` file where we held our babel config. But with webpack encore the  standard is to have babel config inside of your `webpack.config.json`. However this breaks jest, as it no longer knows how to transpile the files.

What is the recommended solution here?

**Comment by stof** [comment]
Encore supports using the babel.config.json file as well. That's a supported use case. Encore automatically detects the presence of a babel config file to choose between using it or managing the config from the webpack config directly.

**Comment by thewalkingcoder** [comment]
I note the behavior change since @symfony/webpack-encore 0.30.x 

I have project with @symfony/webpack-encore 0.28.3 and i have enabled .configureBabelPresetEnv on webpack.config.js and in the same time i have babel.config.js for jest. I can run test and dev-server. (ok, i thinks is not the good approach)

I recently start new project and @symfony/webpack-encore 0.30 is install.
I can't start dev-server because i have error "The "callback" argument of configureBabelPresetEnv() will not be used because your app already provides an external Babel configuration".

Ok i understand my mistake, but how i can  dump the real config to transpose section "babel"  into a babel.config.js

```js

.configureBabelPresetEnv((config) => {
        config.useBuiltIns = 'usage';
        config.corejs = 3;

    })

```
I try that

```js
module.exports = {
    presets: [
        [
            '@babel/preset-env',
            {
                targets: {
                    node: 'current',
                    browsers: [
                        "> 0.5%",
                        "last 2 versions",
                        "IE 11"
                    ]
                },
                useBuiltIns: 'usage',
                corejs : {
                    version: "3",
                    proposals : true
                }
            },
        ],
    ],
};
```
not run
