### ISSUE TITLE
`Encore.copyFiles()` does not support symbolic files

### ISSUE THREAD

**Issue by Kocal** [symfony/webpack-encore#842]
Hi :wave: 

I'm having an issue where using `.copyFiles()` with symbolic files, there are not copied at all.

I'm having two symbolic files:
- `full_page_full_hd_error.png` pointing to `full_hd_error.png`
- `full_page_full_hd_loading.png` pointing to `full_hd_loading.png`

![image](https://user-images.githubusercontent.com/2103975/93993614-3fc13a00-fd8f-11ea-838c-69cddf5fc923.png)

But when running Encore, those two files are missing: 
![image](https://user-images.githubusercontent.com/2103975/93993856-8747c600-fd8f-11ea-989e-1d203f2cd558.png)

I'm using Encore 0.29.1 with the following configuration:
```js
Encore 
  // ...
  .copyFiles([
    {
      from: `./assets/app/images`,
      to: `./images/[path][name].[ext]`,
    },
  ])
```

Thanks

**Comment by Lyrkan** [comment]
Hey @Kocal,

Since `copyFiles(...)` basically uses `require.context(...)` and the `file-loader` internally I'm guessing that at one point Webpack follows those symlinks.

Could you try setting [`resolve.symlinks`](https://webpack.js.org/configuration/resolve/#resolvesymlinks) to `false`?

**Comment by Kocal** [comment]
`resolve.symlinks = false` seems to do the job:
![image](https://user-images.githubusercontent.com/2103975/94065440-6f9e2b00-fdeb-11ea-8ffe-92d3de6f4be9.png)

It does not produce a symbolic link with `public/build/images/screenshots/full_hd_error.png` but I don't think that's an issue.

Should I sent a PR?

**Comment by Lyrkan** [comment]
> Should I send a PR?

I'm not sure that setting `resolve.symlink` to `false` by default in Encore would be a good thing since it could break something else... but I don't see any other good way to fix it :/

Maybe changing `Encore.getWebpackConfig()` to make it return an array with a config that is dedicated to `copyFiles()` (in which `resolve.symlink` would be forced to `false`) would work, but that would be a really heavy change and a big BC break compared to the issue it tries to solve.

If you think that's a problem a lot of people will have maybe adding a note in the documentation would be better?

**Comment by Kocal** [comment]
Nah I think I will just go for this:

```
const config = Encore.getWebpackConfig()
config.resolve.false = true;

return config;
```

Thanks!

**Comment by sovetski** [comment]
> Nah I think I will just go for this:
> 
> ```js
> const config = Encore.getWebpackConfig()
> config.resolve.false = true;
> 
> return config;
> ```
> 
> Thanks!

does not work for me
