### ISSUE TITLE
Manifest key problem with "build cache" + copyFiles with non-fresh cache

### ISSUE THREAD

**Issue by weaverryan** [symfony/webpack-encore#936]
Hi!

I just hit a bug when you combine `Encore.enableBuildCache` with `Encore.copyFiles()`. When you build fresh (no cache, easy to replicate by removing `node_modules/.cache/`), the `manifest.json` contains entries like this:

```json
"build/images/chart.png": "/build/images/chart.db1f878a.png",
```

But if you build again when there is already cache available (easy to replicate by running `yarn watch` and modifying any file), then you get:

```json
"build/images/chart.db1f878a.png": "/build/images/chart.db1f878a.png",
```

Notice they key has the version. 

Btw, my guess is that this is a bug with webpack-manifest-plugin & the build cache, not actually with `copyFiles()`. It's just that `copyFiles()` is the only place in the system that uses `file-loader`... which is probably related.

Cheers!

**Comment by weaverryan** [comment]
I was correct about this being a bug with cache + webpack-manifest-plugin, and I can see why - the `file-loader` is never called... and that library relies on a hook in `file-loader` to collect the filenames.

Interestingly, https://github.com/webdeveric/webpack-assets-manifest does not have this problem. They DO have a different bug related to cache, however - https://github.com/webdeveric/webpack-assets-manifest/issues/131

Anyways, I'll look there for inspiration to see what hooks they're using for file-loader.

**Comment by kl3sk** [comment]
FYI I ran into the problem, disabling `enableBuildCache` resole my problems.

This is how it was configured:

```js
    .enableBuildCache({
        // object of "buildDependencies"
        // https://webpack.js.org/configuration/other-options/#cachebuilddependencies
        // __filename means that changes to webpack.config.js should invalidate the cache
        config: [__filename],
    })

```

**Comment by bobvandevijver** [comment]
@weaverryan I just ran into this issue as well... Did you by any chance find a way to solve this (or another place to file an issue)?

**Comment by weaverryan** [comment]
I haven’t had time to look into it yet - I only know that the https://github.com/webdeveric/webpack-assets-manifest library somehow doesn’t have this problem. But diving into these complex kind to understand what they’re doing differently is... quite tricky.

**Comment by bobvandevijver** [comment]
@weaverryan Looks like it is the exact same issue as described in https://github.com/webdeveric/webpack-assets-manifest/commit/0b323fcdee7105d04cc81a658fdcf7496bc7e383. The [`loaderContext.emitFile`](https://github.com/symfony/webpack-encore/blob/972c8827500f3095dbaff06895a47ac0621bf28e/lib/webpack-manifest-plugin/hooks.js#L132) isn't called when Webpack is run with a valid cache: the whole `file-loader` seems to be skipped... 

Looks like the file-loader is [deprecated](https://v4.webpack.js.org/loaders/file-loader/) anyways for Webpack v5, so that might be why it doesn't work as expected...

The solution the webpack-assets-manifest uses (iterate over the assets to determine their origin) doesn't work at this time for Encore, because the `asset.info` is empty when the assets stats are retrieved.

**Comment by bobvandevijver** [comment]
This can be closed 🎉
