### ISSUE TITLE
Question: How to enable "common-chunk-plugin"? 

### ISSUE THREAD

**Issue by slince** [symfony/webpack-encore#94]

**Comment by weaverryan** [comment]
Use `createSharedEntry()` :) http://symfony.com/doc/current/frontend/encore/shared-entry.html

We should mention the CommonChunkPlugin on that page, and also in `index.js` above this method. This was one method that ultimately had a "different enough" name from the underlying functionality that it's not obvious.

**Comment by weaverryan** [comment]
I'm going to re-open... so I remember to update the docs to mention the plugin by name :

**Comment by pribilinskiy** [comment]
Instead of specifying every vendor librariy, it's better to use the `minChunks` feature

```
commonsChunkPlugin = new webpack.optimize.CommonsChunkPlugin({

	name: 'vendor',

	minChunks(module) {

		return module.context && module.context.match(
			'/('
			+ 'node_modules'
			+ '|public/vendor'
			+ '|assets/vendor'
			+ '|vendor-custom'
			+ ')/'
		);
	}
});
```

**Comment by curry684** [comment]
Can we easily combine this with https://medium.com/@michalozogan/how-to-split-moment-js-locales-to-chunks-with-webpack-de9e25caccea?

**Comment by weaverryan** [comment]
Yes. Mostly, the idea is that you use code splitting - the import function (which requires an extra Babel preset currently, because that is not part of the ES spec officially yet) - so that certain code is loaded async. It really doesn’t have anything to do with the commons chunk plugin - it’s just the idea of loading some stuff async.
